import { test, expect, type Page, type Route } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { publishedText } from "./support/published-text";
import { ASIDE_CEILING, BREATH_CEILING, asideMarks, longestBreath } from "./support/copy-ruler";
import { localizedPathname } from "../../src/i18n/pathnames";
import { LOCALES, DEFAULT_LOCALE } from "../../src/i18n/locales";
import { NAV_ITEMS } from "../../src/lib/nav";
import { documentShape, parseEditorialDocument } from "../../src/lib/editorial-mdx";
import {
  FILTER_FLOOR,
  UPDATES_SECTION,
  getUpdateArticles,
  listUpdates,
  pagerFor,
  showsTypeFilter,
  slugsByLocale,
  updatesFeedPath,
  type UpdateDocument,
} from "../../src/lib/updates";

/**
 * The editorial section of the site — news and release notes.
 *
 * Spec: `docs/design/spec-secao-novidades-site-2026-08.md`.
 *
 * The rules this file proves, and the reason each one is here rather than
 * anywhere else:
 *
 * `DS-COMPONENTE-057` — a route whose **leaf** is translated builds hreflang,
 *   canonical and sitemap from the registry that knows the slug of each locale,
 *   never by handing one string to `buildAlternates`. This is the expensive
 *   one: `localizedPathname` already translates the ancestor, so
 *   `/updates/hour-passes` becomes `/novidades/hour-passes` — the right prefix
 *   with the wrong leaf, a URL that 404s, published as the Portuguese
 *   alternate of all four language versions at once. It looks correct in a
 *   quick inspection, which is exactly why it needs a test and not a reading.
 * `DS-COMPONENTE-051` / `052` / `053` — the card, the order, and the floor the
 *   type filter does not exist below.
 * `DS-COMPONENTE-054` / `055` / `056` / `058` — the closed block set, the
 *   before/after table, the share card generated by route, and the single CTA.
 * `DS-LAYOUT-011` / `012` — the section is in the footer and not in the menu;
 *   the reading column has a measured ceiling.
 * `DS-A11Y-011` — the heading structure belongs to the template.
 * `DS-COPY-046` / `047` / `048` — asides by paragraph, the four locales as one
 *   piece, and the catalogue guard reaching editorial content.
 * `BR-COMUNICACAO-009` — this is the first surface of ours that **dates** an
 *   assertion, so the date has to be machine-readable and identical in the four
 *   languages of one piece.
 * `BR-COMUNICACAO-010` — the ceiling on what may be asserted about the hour
 *   model. The mechanical half is here: no amount is born in an article, and no
 *   article sells access by the day without a declared dispensation.
 *
 * ---------------------------------------------------------------------------
 * Two things this file does NOT do
 * ---------------------------------------------------------------------------
 *
 * 1. **It never reads `page.content()`.** next-intl ships every source string
 *    of every page inside the RSC payload, so the raw HTML of any page contains
 *    the sentence a guard is asserting is absent. `publishedText` strips the
 *    scripts; see `support/published-text.ts`.
 * 2. **It never asserts an accessible name with `toHaveAccessibleName`.** With
 *    whitespace between inline children the matcher normalises the difference
 *    away and passes on a name the browser composes differently. The card's
 *    name is anchored on the `h2` through `aria-labelledby`, and the assertion
 *    reads `textContent`.
 */

const REPO_ROOT = path.resolve(__dirname, "../..");
const CONTENT_DIR = path.join(REPO_ROOT, "src/content/updates");

/** The listing of one locale, as a URL. */
function sectionUrl(locale: string): string {
  return `/${locale}${localizedPathname(locale, UPDATES_SECTION)}`;
}

/** The article of one locale, as a URL — from the registry, never composed. */
function articleUrl(document: UpdateDocument): string {
  return `${sectionUrl(document.locale)}/${document.slug}`;
}

/** Every `.mdx` of the section, with its path relative to the repo root. */
function contentFiles(): { file: string; raw: string }[] {
  if (!fs.existsSync(CONTENT_DIR)) return [];
  return fs
    .readdirSync(CONTENT_DIR)
    .flatMap((id) => {
      const dir = path.join(CONTENT_DIR, id);
      if (!fs.statSync(dir).isDirectory()) return [];
      return fs
        .readdirSync(dir)
        .filter((name) => name.endsWith(".mdx"))
        .map((name) => ({
          file: path.relative(REPO_ROOT, path.join(dir, name)),
          raw: fs.readFileSync(path.join(dir, name), "utf8"),
        }));
    });
}

/** Answers /api/geo with a country, before anything on the page asks —
 *  the same double `base-market-price.spec.ts` uses. */
async function geoAnswers(page: Page, country: string | null): Promise<void> {
  await page.route("**/api/geo", (route: Route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ country }),
    })
  );
}

/* ---------------------------------------------------------------------------
 * 1. The routes, and the trap
 * ------------------------------------------------------------------------- */

test.describe("Routes — the section and the article answer at the translated slug", () => {
  for (const locale of LOCALES) {
    test(`DS-COPY-006: /${locale}${localizedPathname(locale, UPDATES_SECTION)} answers 200`, async ({
      request,
    }) => {
      const response = await request.get(sectionUrl(locale), { maxRedirects: 0 });
      expect(response.status(), `${sectionUrl(locale)} is the declared slug of ${locale}`).toBe(200);
    });

    test(`DS-COMPONENTE-057: every article of ${locale} answers at its own leaf`, async ({
      request,
    }) => {
      const listing = listUpdates(locale);
      expect(listing.length, `${locale} publishes no article; the section has nothing to prove`)
        .toBeGreaterThan(0);

      for (const document of listing) {
        const response = await request.get(articleUrl(document), { maxRedirects: 0 });
        expect(response.status(), articleUrl(document)).toBe(200);
      }
    });
  }

  test("DS-COMPONENTE-057: the leaf of ANOTHER language does not serve the piece", async ({
    request,
  }) => {
    // THE FAILURE THIS EXISTS FOR. `localizedPathname` translates the ancestor
    // and carries the leaf through, so `/pt/novidades/hour-passes` is exactly
    // what a hreflang built by string concatenation would publish. It has to be
    // a 404 and not a page: an address that answers 200 in two languages is two
    // canonical URLs for one piece.
    const foreign: string[] = [];
    for (const article of getUpdateArticles()) {
      const leaves = slugsByLocale(article.id);
      for (const locale of LOCALES) {
        const own = leaves[locale];
        for (const [otherLocale, otherLeaf] of Object.entries(leaves)) {
          if (otherLocale === locale || otherLeaf === own) continue;
          foreign.push(`${sectionUrl(locale)}/${otherLeaf}`);
        }
      }
    }
    expect(foreign.length, "no article has two different leaves to cross").toBeGreaterThan(0);

    for (const url of foreign) {
      const response = await request.get(url, { maxRedirects: 0 });
      expect(response.status(), `${url} serves a piece at an address nothing links to`).toBe(404);
    }
  });

  test("DS-COPY-006: the untranslated section word never serves a second copy", async ({
    request,
  }) => {
    // `/pt/updates` is the internal pathname under a locale that translates it.
    // next-intl answers a redirect to the canonical `/pt/novidades` rather than
    // a 404 — which is the behaviour we want and NOT what the spec's criterion
    // 1 predicted. What matters is the same either way: the internal word never
    // answers 200 with a second copy of the page.
    for (const locale of LOCALES) {
      const internal = `/${locale}${UPDATES_SECTION}`;
      if (internal === sectionUrl(locale)) continue;
      const response = await request.get(internal, { maxRedirects: 0 });
      expect([301, 302, 307, 308, 404], `${internal} answered ${response.status()}`).toContain(
        response.status()
      );
    }
  });
});

/* ---------------------------------------------------------------------------
 * 2. hreflang, canonical and the share card
 * ------------------------------------------------------------------------- */

test.describe("DS-COMPONENTE-057 — hreflang of an article comes from the registry", () => {
  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-057: hreflang on ${locale} names each locale's own leaf`, async ({
      request,
    }) => {
      for (const document of listUpdates(locale)) {
        const response = await request.get(articleUrl(document));
        expect(response.status()).toBe(200);
        const html = await response.text();

        const alternates = Object.fromEntries(
          [
            ...html.matchAll(/<link rel="alternate" hrefLang="([^"]+)" href="([^"]+)"/g),
          ].map((match) => [match[1], new URL(match[2]).pathname])
        );

        const leaves = slugsByLocale(document.id);
        const expected: Record<string, string> = {};
        for (const [other, leaf] of Object.entries(leaves)) {
          expected[other] = `${sectionUrl(other)}/${leaf}`;
        }
        // DS-COPY-047: only the locales the piece exists in. Pointing at a
        // translation that is not there is how all four are lost at once.
        expected["x-default"] = expected[DEFAULT_LOCALE] ?? Object.values(expected)[0];

        expect(alternates, `hreflang on ${articleUrl(document)}`).toEqual(expected);

        // And every address it names resolves.
        for (const href of new Set(Object.values(alternates))) {
          const alternate = await request.get(href, { maxRedirects: 0 });
          expect(alternate.status(), `alternate ${href}`).toBe(200);
        }
      }
    });

    test(`DS-COMPONENTE-056: og:image is the route, and og:image:alt is in ${locale}`, async ({
      page,
    }) => {
      for (const document of listUpdates(locale)) {
        await page.goto(articleUrl(document));

        const image = await page
          .locator('meta[property="og:image"]')
          .first()
          .getAttribute("content");
        // The INTERNAL path: the generated route is
        // `[locale]/updates/[slug]/opengraph-image`, and the localized pattern
        // `/novidades/[slug]` matches one segment, not two.
        expect(image, "og:image does not point at this article's own card").toContain(
          `/${locale}${UPDATES_SECTION}/${document.slug}/opengraph-image`
        );

        const alt = await page
          .locator('meta[property="og:image:alt"]')
          .first()
          .getAttribute("content");
        // The `alt` export of an opengraph-image is static and never sees
        // `params` — this is the whole reason the page keeps `openGraph.images`
        // instead of letting the file convention take over.
        expect(alt, "og:image:alt is not this locale's").toBe(document.ogAlt);
      }
    });

    test(`DS-COMPONENTE-056: the ${locale} share card answers 200 at 1200 × 630`, async ({
      request,
    }) => {
      for (const document of listUpdates(locale)) {
        const url = `/${locale}${UPDATES_SECTION}/${document.slug}/opengraph-image`;
        const response = await request.get(url);
        expect(response.status(), url).toBe(200);
        expect(response.headers()["content-type"]).toContain("image/png");

        // The IHDR of a PNG carries the size in bytes 16–23; reading it is
        // cheaper and more honest than trusting the route's `size` export.
        const body = await response.body();
        expect(body.readUInt32BE(16), `${url} width`).toBe(1200);
        expect(body.readUInt32BE(20), `${url} height`).toBe(630);
      }
    });

    test(`the ${locale} <title> does not name the brand twice`, async ({ request }) => {
      // The root layout appends "| TUGGI"; a frontmatter title that names it
      // would publish it twice in the one string a search result shows.
      for (const url of [sectionUrl(locale), ...listUpdates(locale).map(articleUrl)]) {
        const html = await (await request.get(url)).text();
        const title = /<title>([^<]*)<\/title>/.exec(html)?.[1] ?? "";
        expect(title, `${url} has no <title>`).not.toBe("");
        expect(
          (title.match(/TUGGI/gi) ?? []).length,
          `${url} publishes "${title}"`
        ).toBeLessThanOrEqual(1);
      }
    });
  }
});

/* ---------------------------------------------------------------------------
 * 3. The discovery surfaces
 * ------------------------------------------------------------------------- */

test.describe("The section is discoverable, or it is invisible", () => {
  test("DS-LAYOUT-011: /llms.txt carries the section and one line per article", async ({
    request,
  }) => {
    const body = await (await request.get("/llms.txt")).text();
    expect(body, "the AI-readable map has no Updates section").toContain("## Updates");
    expect(body).toContain(`${sectionUrl(DEFAULT_LOCALE)}`);

    for (const article of getUpdateArticles()) {
      const document = article.byLocale[DEFAULT_LOCALE] ?? Object.values(article.byLocale)[0];
      expect(body, `${article.id} is missing from /llms.txt`).toContain(articleUrl(document));
      expect(body, `${article.id} has no title in /llms.txt`).toContain(document.title);
    }
  });

  test("DS-LAYOUT-011: the sitemap carries the section and every article, per locale", async ({
    request,
  }) => {
    const xml = await (await request.get("/sitemap.xml")).text();

    for (const locale of LOCALES) {
      expect(xml, `${sectionUrl(locale)} is missing from the sitemap`).toContain(
        `https://www.tuggi.app${sectionUrl(locale)}<`
      );
      for (const document of listUpdates(locale)) {
        expect(xml, `${articleUrl(document)} is missing from the sitemap`).toContain(
          `https://www.tuggi.app${articleUrl(document)}<`
        );
      }
    }
  });

  test("DS-LAYOUT-011: the section is NOT an item of the main menu", () => {
    // The cold visitor's path is promise → proof → install. A reading
    // destination in a header that already carries six items, a language picker
    // and the download CTA is a seventh decision in it.
    //
    // Asserted on the registry and not on the rendered header, and the reason is
    // a false positive that cost a run: the language switcher lives INSIDE
    // `nav[data-nav-scope="desktop"]` and links the current page in the four
    // locales, so on the listing itself the header legitimately carries
    // `/en/updates`, `/pt/novidades`, `/es/novedades` and `/it/aggiornamenti`.
    // Those are the same page in another language, not a menu entry. What the
    // rule forbids is an ITEM, and the items are `NAV_ITEMS`.
    expect(
      NAV_ITEMS.map((item) => item.href),
      "the editorial section reached the main menu"
    ).not.toContain(UPDATES_SECTION);
  });

  for (const locale of LOCALES) {
    test(`DS-LAYOUT-011: the ${locale} footer carries the section`, async ({ page }) => {
      // The footer is one of the four doors, and the only one a human clicks —
      // the other three are the sitemap, /llms.txt and a direct link.
      await page.goto(`/${locale}`);
      await expect(
        page.locator(`footer a[href="${sectionUrl(locale)}"]`),
        "the section has no door in this locale"
      ).toHaveCount(1);
    });
  }

  test("the RSS feed of each locale answers with that locale's listing", async ({ request }) => {
    for (const locale of LOCALES) {
      const url = updatesFeedPath(locale);
      const response = await request.get(url);
      expect(response.status(), url).toBe(200);
      expect(response.headers()["content-type"]).toContain("application/rss+xml");

      const body = await response.text();
      // The address carries a dot, so the middleware never rewrites it — the
      // feed lives at the internal path, like /sitemap.xml and /llms.txt.
      expect(body).toContain(`<atom:link href="https://www.tuggi.app${url}"`);
      for (const document of listUpdates(locale)) {
        expect(body, `${articleUrl(document)} is missing from the ${locale} feed`).toContain(
          `https://www.tuggi.app${articleUrl(document)}`
        );
      }
    }
  });
});

/* ---------------------------------------------------------------------------
 * 4. The listing
 * ------------------------------------------------------------------------- */

test.describe("DS-COMPONENTE-051 / 052 — the listing and its card", () => {
  test("DS-COMPONENTE-052: the order is strictly descending by date, ties on the slug", () => {
    for (const locale of LOCALES) {
      const listing = listUpdates(locale);
      const sorted = [...listing].sort((a, b) =>
        a.publishedAt === b.publishedAt
          ? a.slug.localeCompare(b.slug)
          : b.publishedAt.localeCompare(a.publishedAt)
      );
      expect(listing.map((d) => d.slug), `${locale} is out of order`).toEqual(
        sorted.map((d) => d.slug)
      );
    }
  });

  test("DS-COMPONENTE-053: below the floor there is no filter control in the DOM", async ({
    page,
  }) => {
    // The floor is per locale, because the listing is per locale: 12 articles
    // AND at least 3 of each type. A control for a list that fits in one glance
    // is furniture. When a locale crosses the floor this goes red, which is the
    // trip-wire that opens the card.
    for (const locale of LOCALES) {
      const listing = listUpdates(locale);
      expect(
        showsTypeFilter(listing),
        `${locale} has ${listing.length} articles and crossed the floor of ` +
          `${FILTER_FLOOR.articles}/${FILTER_FLOOR.perType} — the filter of DS-COMPONENTE-053 is now due`
      ).toBe(false);

      await page.goto(sectionUrl(locale));
      await expect(
        page.locator('[data-block="update-type-filter"]'),
        `${locale} renders a filter the floor does not allow`
      ).toHaveCount(0);
    }
  });

  for (const [width, columns] of [
    [1280, 3],
    [700, 2],
    [360, 1],
  ] as const) {
    test(`DS-COMPONENTE-051: the grid has ${columns} column(s) at ${width} px, and no card under 300 px`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(sectionUrl(DEFAULT_LOCALE));

      const grid = page.locator("main div.grid").first();
      const measured = await grid.evaluate((node) => ({
        columns: getComputedStyle(node).gridTemplateColumns.split(" ").filter(Boolean).length,
        cardWidths: [...node.children].map((child) => child.getBoundingClientRect().width),
      }));

      // Three and not four, measured: at 1280 the rail gives 1216 px, and with
      // gap-6 three columns are 389 px — where the clamped summary breaks at
      // ~48 characters. Four give 286 px and three lines become a fragment.
      expect(measured.columns, `${width} px`).toBe(columns);
      for (const cardWidth of measured.cardWidths) {
        expect(cardWidth, `a card measures ${cardWidth} px at ${width} px`).toBeGreaterThanOrEqual(
          300
        );
      }
    });
  }

  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-051: on ${locale} every card is one tab stop named by its title`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1280, height: 900 });
      await page.goto(sectionUrl(locale));

      const listing = listUpdates(locale);
      for (const document of listing) {
        const card = page.locator(`main a[href="${articleUrl(document)}"]`);
        // One target per card: the affordance is not a second anchor, because
        // two links to one destination are two keyboard stops for one decision.
        await expect(card, `${document.slug} is linked more than once`).toHaveCount(1);

        // NOT toHaveAccessibleName: whitespace between inline children makes
        // that matcher normalise a real difference away. The name is anchored
        // on the h2 by aria-labelledby, so the h2's text IS the name.
        const labelledBy = await card.getAttribute("aria-labelledby");
        expect(labelledBy, "the card composes its name out of everything inside it").toBeTruthy();
        const name = await page.locator(`#${labelledBy}`).evaluate((node) => node.textContent ?? "");
        expect(name.trim()).toBe(document.title);
      }
    });

    test(`DS-COMPONENTE-051: on ${locale} the cards of a row are the same height`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1280, height: 900 });
      await page.goto(sectionUrl(locale));

      const heights = await page
        .locator("main div.grid > a")
        .evaluateAll((nodes) =>
          nodes.map((node) => Math.round(node.getBoundingClientRect().height))
        );
      expect(heights.length).toBeGreaterThan(0);
      expect(new Set(heights).size, `card heights in ${locale}: ${heights.join(", ")}`).toBe(1);
    });
  }

  test("DS-COPY-047: the empty state of a locale with no article is translated", () => {
    // Every locale publishes the first article today, so the empty state has no
    // page to be measured on. What CAN go wrong without anybody noticing is a
    // missing translation, which next-intl publishes as the key name — and that
    // is what this checks. The rendered state joins the day a locale is behind.
    for (const locale of LOCALES) {
      const messages = JSON.parse(
        fs.readFileSync(path.join(REPO_ROOT, "src/messages", `${locale}.json`), "utf8")
      );
      for (const key of ["body", "link"] as const) {
        const value = messages.Updates?.empty?.[key];
        expect(value, `Updates.empty.${key} is missing from ${locale}.json`).toBeTruthy();
        expect(value, `Updates.empty.${key} renders its own name in ${locale}`).not.toContain(
          "Updates.empty"
        );
      }
    }
  });
});

/* ---------------------------------------------------------------------------
 * 5. The article
 * ------------------------------------------------------------------------- */

test.describe("DS-A11Y-011 — the heading structure belongs to the template", () => {
  for (const locale of LOCALES) {
    test(`DS-A11Y-011: on ${locale} the article has one h1 and no level skip`, async ({ page }) => {
      // The loop variable is `piece` and not `document`: inside `page.evaluate`
      // the callback is type-checked in THIS scope, so an outer `document`
      // shadows the DOM one and the compiler resolves `querySelectorAll`
      // against an article.
      for (const piece of listUpdates(locale)) {
        await page.goto(articleUrl(piece));

        const headings = await page.evaluate(() =>
          Array.from(document.querySelectorAll("h1, h2, h3, h4, h5, h6")).map((element) => ({
            level: Number(element.tagName.slice(1)),
            text: (element.textContent ?? "").trim().slice(0, 60),
          }))
        );

        expect(headings.filter((h) => h.level === 1), "one <h1> per document").toHaveLength(1);
        expect(headings[0]?.level, "the first heading of the document is the <h1>").toBe(1);

        const skips = headings
          .slice(1)
          .map((heading, index) => ({ heading, previous: headings[index] }))
          .filter(({ heading, previous }) => heading.level > previous.level + 1)
          .map(({ heading, previous }) => `h${previous.level} → h${heading.level} (${heading.text})`);
        expect(skips, "heading levels step by one on the way down").toEqual([]);

        // The root layout owns `<main id="main-content">`; a second landmark of
        // the same role inside it is the defect trust-center/layout.tsx fixed.
        expect(await page.locator("main, [role=main]").count()).toBe(1);
        await expect(page.locator("html")).toHaveAttribute("lang", locale);
      }
    });
  }

  test("DS-COPY-047: the four locales of one piece have the same tree", () => {
    // Not the same text — the same SHAPE. If `pt` has four `h2` and `en` has
    // six, the same article answers different questions depending on the
    // language, and the citation that comes back to us is whichever one
    // somebody wrote with more enthusiasm.
    for (const article of getUpdateArticles()) {
      const shapes = Object.entries(article.byLocale).map(
        ([locale, document]) => [locale, documentShape(document.blocks)] as const
      );
      const [reference, referenceShape] = shapes[0];
      for (const [locale, shape] of shapes.slice(1)) {
        expect(
          shape,
          `${article.id}: ${locale} and ${reference} are not the same piece`
        ).toEqual(referenceShape);
      }
    }
  });

  test("BR-COMUNICACAO-009: the date of a piece is machine-readable and one per piece", async ({
    page,
  }) => {
    // This is the first surface of ours that DATES an assertion: a product page
    // describes today's offer and corrects itself when the product changes, and
    // an article of 2026-08-30 keeps saying 2026-08-30 forever. So the date is
    // in the markup, not only in a formatted sentence — and it is the same date
    // in the four languages, because they are one piece.
    for (const article of getUpdateArticles()) {
      for (const document of Object.values(article.byLocale)) {
        expect(document.publishedAt).toBe(article.publishedAt);
        await page.goto(articleUrl(document));
        await expect(page.locator(`time[datetime="${article.publishedAt}"]`).first()).toBeVisible();

        const served = await publishedText(page);
        expect(served, "the structured data does not carry the publication date").toContain(
          article.publishedAt
        );
      }
    }
  });
});

test.describe("DS-LAYOUT-012 — the reading column has a measured ceiling", () => {
  for (const width of [1024, 1440]) {
    test(`DS-LAYOUT-012: at ${width} px text stays under 576 px and a figure under 768 px`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 1000 });
      const document = listUpdates(DEFAULT_LOCALE)[0];
      await page.goto(articleUrl(document));

      // 576 px ÷ 8,06 px (the mean glyph of this copy at Inter 16/28) is 71
      // characters, inside the 45–75 band. The legal pages measure 822 px and
      // 102 characters, because they cancel the measure with `max-w-none` —
      // that is a consultation surface, and this is a reading one.
      // Scoped to the BODY, which is what "reading column" means: the dek is a
      // single display sentence in the header, at `text-lg`, and it sits in the
      // figure column with the `h1` on purpose (§5.1). The 45–75 band is about
      // running text.
      const paragraphs = await page
        .locator("article .prose p")
        .evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect().width));
      expect(paragraphs.length).toBeGreaterThan(0);
      for (const paragraphWidth of paragraphs) {
        expect(Math.round(paragraphWidth), "a paragraph runs past the reading column").toBeLessThanOrEqual(
          576
        );
      }

      const wide = await page
        .locator("article figure, article table")
        .evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect().width));
      expect(wide.length).toBeGreaterThan(0);
      for (const wideWidth of wide) {
        expect(Math.round(wideWidth), "a figure or table runs past the figure column").toBeLessThanOrEqual(
          768
        );
      }
    });
  }
});

test.describe("DS-COMPONENTE-054 / 055 — the closed block set", () => {
  test("DS-COMPONENTE-054: the article renders every block the marker exercises", async ({
    page,
  }) => {
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    await expect(page.locator("article figure blockquote"), "the quote block").toHaveCount(1);
    await expect(page.locator("article aside"), "the notice block").toHaveCount(1);
    await expect(page.locator("article table"), "the change table and the price table").toHaveCount(
      2
    );
    // The cover figure plus the body figure.
    await expect(page.locator("article figure img"), "the figure block").toHaveCount(1);
    await expect(page.locator("article ul, article ol"), "the list block").not.toHaveCount(0);
  });

  test("DS-COMPONENTE-055: before/after is one table with a caption and two column headers", async ({
    page,
  }) => {
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    const table = page.locator("article table").first();
    await expect(table.locator("caption")).toHaveCount(1);
    await expect(table.locator('th[scope="col"]')).toHaveCount(2);
  });

  test("DS-COMPONENTE-055: at 360 px the pair of a row stays adjacent", async ({ page }) => {
    // The reading this block exists to prevent is two separate lists. A
    // `display: block` "responsive table" delivers exactly that and drops the
    // header association on the way, so the table stays a table at every width.
    await page.setViewportSize({ width: 360, height: 900 });
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    const row = page.locator("article table tbody tr").first();
    const boxes = await row
      .locator("td")
      .evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect()));
    expect(boxes).toHaveLength(2);
    // Side by side, not stacked: the two cells share a line.
    expect(
      Math.abs(boxes[0].top - boxes[1].top),
      "the two sides of one row split into two stacks"
    ).toBeLessThan(4);
  });

  test("DS-COMPONENTE-058: the end of an article has one CTA and a pager", async ({ page }) => {
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    // One store CTA, and it is the one the site already publishes. No
    // newsletter, no "follow us", and no third-party share widget — a share
    // script would enter the AttributionGateProvider and the CookieBanner this
    // site already operates, and would cost weight on a phone.
    const storeCta = page.locator('article a[href="/d/tuggi"], article a[href^="https://apps.apple"]');
    await expect(storeCta).toHaveCount(1);

    // With one article the pager has no neighbour and renders nothing, which is
    // the correct answer — `pagerFor` is proved below on a list that has them.
    const { previous, next } = pagerFor(listUpdates(DEFAULT_LOCALE), document.slug);
    await expect(page.locator("article nav")).toHaveCount(previous || next ? 1 : 0);
  });

  test("DS-COMPONENTE-058: the pager is previous-older / next-newer", () => {
    const listing = [
      { slug: "c", publishedAt: "2026-03-01" },
      { slug: "b", publishedAt: "2026-02-01" },
      { slug: "a", publishedAt: "2026-01-01" },
    ] as unknown as UpdateDocument[];

    expect(pagerFor(listing, "b").previous?.slug, "previous is the older piece").toBe("a");
    expect(pagerFor(listing, "b").next?.slug, "next is the newer piece").toBe("c");
    expect(pagerFor(listing, "c").next, "the newest piece has nothing newer").toBeNull();
    expect(pagerFor(listing, "a").previous, "the oldest piece has nothing older").toBeNull();
  });
});

test.describe("DS-MARCA-009 — alt, and what the generated cover is not", () => {
  for (const locale of LOCALES) {
    test(`DS-MARCA-009: every content image on ${locale} carries a real alt`, async ({ page }) => {
      for (const document of listUpdates(locale)) {
        await page.goto(articleUrl(document));

        const alts = await page
          .locator("article img")
          .evaluateAll((nodes) => nodes.map((node) => (node as HTMLImageElement).alt));

        for (const alt of alts) {
          expect(alt.trim(), "a content image has no description").not.toBe("");
          // The screen reader heard the title two elements ago.
          expect(alt.trim().toLowerCase()).not.toBe(document.title.trim().toLowerCase());
        }

        if (document.cover === "generated") {
          // The generated field carries no text and no logo, and is therefore
          // decorative: it is drawn inline and hidden from assistive technology
          // rather than described with an empty string over HTTP.
          const cover = page.locator("article header figure svg").first();
          await expect(cover).toHaveAttribute("aria-hidden", "true");
          await expect(page.locator("article header figure img")).toHaveCount(0);
        }
      }
    });
  }
});

/* ---------------------------------------------------------------------------
 * 6. The price — BR-MONETIZACAO-069, and BR-COMUNICACAO-010's mechanical half
 * ------------------------------------------------------------------------- */

const PRICE_IN_PROSE = /(R\$|US\$|\bUSD\b|\bBRL\b|\bEUR\b|€|£|\$\s?\d)|\b\d+[.,]\d{2}\b/;

test.describe("BR-MONETIZACAO-069 — the article reads the price table, it never types it", () => {
  test("BR-COMUNICACAO-010: no amount is written into any .mdx", () => {
    // The dispensation of DS-COPY-048 does not exist for a price: a price on
    // the site is born in `src/lib/pricing.ts` and nowhere else, and an article
    // has no reason to type one. A number in content survives the market it
    // belongs to and is never formatted by `Intl`.
    const offenders = contentFiles()
      .flatMap(({ file, raw }) =>
        raw
          .split("\n")
          .map((line, index) => ({ file, line: index + 1, text: line }))
          .filter(({ text }) => PRICE_IN_PROSE.test(text))
      )
      .map(({ file, line, text }) => `${file}:${line}: ${text.trim()}`);

    expect(offenders).toEqual([]);
  });

  test("BR-MONETIZACAO-069: outside a base market the table shows the store note, with no number", async ({
    page,
  }) => {
    await geoAnswers(page, "MX");
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    const block = page.locator('[data-block="article-price-table"]');
    await expect(block).toHaveCount(1);
    const text = await block.innerText();

    expect(text, "an amount was published outside the three base markets").not.toMatch(
      PRICE_IN_PROSE
    );
    expect(text, "the store note names neither store").toContain("App Store");
    expect(text, "the store note names neither store").toContain("Google Play");
  });

  test("BR-MONETIZACAO-069: inside a base market the table shows the three amounts", async ({
    page,
  }) => {
    await geoAnswers(page, "BR");
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    const block = page.locator('[data-block="article-price-table"]');
    // Written out here independently of `src/lib/pricing.ts`, so changing a
    // number on either side goes red — the table is what the site charges
    // people to believe (BR-MONETIZACAO-048).
    for (const amount of ["9.90", "19.90", "29.90"]) {
      await expect(block, `the ${amount} row`).toContainText(amount);
    }
  });

  test("BR-MONETIZACAO-069: the geo answer decides, and an unknown country is not a market", async ({
    page,
  }) => {
    await geoAnswers(page, null);
    const document = listUpdates(DEFAULT_LOCALE)[0];
    await page.goto(articleUrl(document));

    const text = await page.locator('[data-block="article-price-table"]').innerText();
    expect(text, '"I do not know where you are" published an offer').not.toMatch(PRICE_IN_PROSE);
  });
});

/* ---------------------------------------------------------------------------
 * 7. The content contract — parse time, so it breaks the build
 * ------------------------------------------------------------------------- */

test.describe("DS-COPY-046 / DS-A11Y-011 — what the content files may contain", () => {
  test("DS-A11Y-011: no `#` opens a line in any body", () => {
    for (const { file, raw } of contentFiles()) {
      const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "");
      const offenders = body
        .split("\n")
        .map((line, index) => ({ line: index + 1, text: line }))
        .filter(({ text }) => /^#(?!#)/.test(text))
        .map(({ line, text }) => `${file}:${line}: ${text}`);
      expect(offenders, "the `h1` belongs to the template").toEqual([]);
    }
  });

  test("DS-COPY-046: asides are counted per paragraph, with a ceiling per piece", () => {
    // The unit is the paragraph, because an article has no i18n key. The four
    // marks count TOGETHER — a guard matching only `[—–]` passes green in
    // Spanish, which translates the same asides with a colon.
    for (const { file, raw } of contentFiles()) {
      const { blocks } = parseEditorialDocument(raw, file);
      const paragraphs = blocks
        .filter((block) => block.kind === "paragraph")
        .map((block) =>
          block.kind === "paragraph"
            ? block.children
                .map((node) => (node.kind === "text" ? node.value : ""))
                .join("")
            : ""
        );

      expect(paragraphs.length, `${file} has no paragraph to measure`).toBeGreaterThan(0);

      const withAside = paragraphs.filter((text) => asideMarks(text) > 0);
      for (const text of paragraphs) {
        expect(asideMarks(text), `${file}: "${text.slice(0, 70)}"`).toBeLessThanOrEqual(
          ASIDE_CEILING
        );
        expect(longestBreath(text), `${file}: "${text.slice(0, 70)}"`).toBeLessThanOrEqual(
          BREATH_CEILING
        );
      }
      expect(
        withAside.length * 3,
        `${file}: ${withAside.length} of ${paragraphs.length} paragraphs carry an aside`
      ).toBeLessThanOrEqual(paragraphs.length);
    }
  });

  test("DS-COMPONENTE-054: an unknown tag, a style or a className is a parse error", () => {
    const frontmatter = [
      "---",
      "slug: x",
      "title: T",
      "summary: S",
      "type: news",
      "publishedAt: 2026-01-01",
      "cover: generated",
      "ogAlt: A",
      "---",
      "",
    ].join("\n");

    const refused: [string, string][] = [
      ["an undeclared component", '<ArticleCarousel src="a" />'],
      ["an inline style", '<ArticleNotice body="a" style="color:red" />'],
      ["a utility class", '<ArticleNotice body="a" className="text-red-500" />'],
      ["a figure with no alt", '<ArticleFigure src="/a.png" />'],
      ["an anonymous quotation", '<ArticleQuote quote="a" />'],
      ["a blank cell in before/after", '<ArticleChangeTable caption="c" beforeLabel="b" afterLabel="a" rows={[["x", ""]]} />'],
      ["an `h1` in the body", "# a heading the template owns"],
      ["an `h3` with no `h2` above it", "### orphan"],
    ];

    for (const [why, body] of refused) {
      expect(
        () => parseEditorialDocument(frontmatter + body + "\n", "<test>"),
        `${why} was accepted`
      ).toThrow();
    }
  });

  test("DS-COPY-048: a waiver with no reason is refused, and one with a reason is kept", () => {
    const base = [
      "---",
      "slug: x",
      "title: T",
      "summary: S",
      "type: news",
      "publishedAt: 2026-01-01",
      "cover: generated",
      "ogAlt: A",
    ].join("\n");

    const withReason = parseEditorialDocument(
      `${base}\nwaiver:\n  - rule: ACCESS_IN_DAYS\n    reason: "BR-MONETIZACAO-062 — the piece explains the extinction"\n---\n\nA paragraph.\n`,
      "<test>"
    );
    expect(withReason.frontmatter.waiver).toEqual([
      {
        rule: "ACCESS_IN_DAYS",
        reason: "BR-MONETIZACAO-062 — the piece explains the extinction",
      },
    ]);
  });

  test("TEMPORARY: the article #1 is still marked as provisional", () => {
    // The body of the first article is placeholder text on purpose: the copy is
    // the `design`'s and lands in the next round. This assertion is the guard
    // against the failure mode that has burned other teams — placeholder that
    // reads like real copy gets published and nobody notices.
    //
    // WHEN THE REAL COPY LANDS, THIS TEST IS DELETED IN THE SAME COMMIT. It is
    // not a rule; it is a marker with a deadline, and it goes red the moment
    // somebody half-replaces the text.
    const markers = /TEXTO PROVISÓRIO|PLACEHOLDER TEXT|TEXTO PROVISIONAL|TESTO PROVVISORIO/;
    for (const { file, raw } of contentFiles()) {
      expect(raw, `${file} no longer declares itself provisional`).toMatch(markers);
    }
  });
});
