import { test, expect, type Page, type Route } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import { publishedText } from "./support/published-text";
import { ASIDE_CEILING, BREATH_CEILING, asideMarks, longestBreath } from "./support/copy-ruler";
import { localizedPathname } from "../../src/i18n/pathnames";
import { LOCALES, DEFAULT_LOCALE } from "../../src/i18n/locales";
import { ARTICLE_RAIL_ITEMS, NAV_ITEMS } from "../../src/lib/nav";
import {
  AUTHORABLE_BLOCKS,
  documentShape,
  parseEditorialDocument,
  type AuthorableBlock,
} from "../../src/lib/editorial-mdx";
import {
  FILTER_FLOOR,
  LISTING_CEILING,
  UPDATES_SECTION,
  getUpdateArticles,
  listUpdates,
  pagerFor,
  showsTypeFilter,
  slugsByLocale,
  updatesFeedPath,
  type UpdateDocument,
} from "../../src/lib/updates";

/**
 * The editorial section of the site — news and release notes.
 *
 * Spec: `docs/design/spec-secao-novidades-site-2026-08.md`.
 *
 * The rules this file proves, and the reason each one is here rather than
 * anywhere else:
 *
 * `DS-COMPONENTE-057` — a route whose **leaf** is translated builds hreflang,
 *   canonical and sitemap from the registry that knows the slug of each locale,
 *   never by handing one string to `buildAlternates`. This is the expensive
 *   one: `localizedPathname` already translates the ancestor, so
 *   `/updates/hour-passes` becomes `/novidades/hour-passes` — the right prefix
 *   with the wrong leaf, a URL that 404s, published as the Portuguese
 *   alternate of all four language versions at once. It looks correct in a
 *   quick inspection, which is exactly why it needs a test and not a reading.
 * `DS-COMPONENTE-051` / `052` / `053` — the card, the order, and the floor the
 *   type filter does not exist below.
 * `DS-COMPONENTE-054` / `055` / `056` / `058` — the closed block set, the
 *   before/after table, the share card generated by route, and the single CTA.
 * `DS-LAYOUT-011` / `012` — the section is in the footer and not in the menu;
 *   the reading column has a measured ceiling.
 * `DS-A11Y-011` — the heading structure belongs to the template.
 * `DS-COPY-046` / `047` / `048` — asides by paragraph, the four locales as one
 *   piece, and the catalogue guard reaching editorial content.
 * `BR-COMUNICACAO-009` — this is the first surface of ours that **dates** an
 *   assertion, so the date has to be machine-readable and identical in the four
 *   languages of one piece.
 * `BR-COMUNICACAO-010` — the ceiling on what may be asserted about the hour
 *   model. The mechanical half is here: no amount is born in an article, and no
 *   article sells access by the day without a declared dispensation.
 *
 * ---------------------------------------------------------------------------
 * Two things this file does NOT do
 * ---------------------------------------------------------------------------
 *
 * 1. **It never reads `page.content()`.** next-intl ships every source string
 *    of every page inside the RSC payload, so the raw HTML of any page contains
 *    the sentence a guard is asserting is absent. `publishedText` strips the
 *    scripts; see `support/published-text.ts`.
 * 2. **It never asserts an accessible name with `toHaveAccessibleName`.** With
 *    whitespace between inline children the matcher normalises the difference
 *    away and passes on a name the browser composes differently. The card's
 *    name is anchored on the `h2` through `aria-labelledby`, and the assertion
 *    reads `textContent`.
 */

const REPO_ROOT = path.resolve(__dirname, "../..");
const CONTENT_DIR = path.join(REPO_ROOT, "src/content/updates");

/** The listing of one locale, as a URL. */
function sectionUrl(locale: string): string {
  return `/${locale}${localizedPathname(locale, UPDATES_SECTION)}`;
}

/** The article of one locale, as a URL — from the registry, never composed. */
function articleUrl(document: UpdateDocument): string {
  return `${sectionUrl(document.locale)}/${document.slug}`;
}

/**
 * The article that declares a given block — the anchor of every block test.
 *
 * NOT `listUpdates(locale)[0]`. That reads "the newest piece", which is a
 * property of the publication calendar and of the slug that breaks the tie; it
 * stood in for "the piece with the blocks" only while the section held one
 * article. The second piece, published on the same day, sorted ahead of the
 * first, and five block assertions went red at once for a reason that had
 * nothing to do with the block set. The anchor is the declaration, which is
 * what each of those tests is about.
 */
function articleDeclaring(locale: string, name: AuthorableBlock): UpdateDocument {
  const found = listUpdates(locale as UpdateDocument["locale"]).find((document) =>
    document.blocks.some((block) => block.kind === "component" && block.name === name)
  );
  if (!found) {
    throw new Error(
      `no ${locale} article declares <${name}>, so this test has nothing to stand on — ` +
        "delete it, or point it at a piece that carries the block"
    );
  }
  return found;
}

/** Every `.mdx` of the section, with its path relative to the repo root. */
function contentFiles(): { file: string; raw: string }[] {
  if (!fs.existsSync(CONTENT_DIR)) return [];
  return fs
    .readdirSync(CONTENT_DIR)
    .flatMap((id) => {
      const dir = path.join(CONTENT_DIR, id);
      if (!fs.statSync(dir).isDirectory()) return [];
      return fs
        .readdirSync(dir)
        .filter((name) => name.endsWith(".mdx"))
        .map((name) => ({
          file: path.relative(REPO_ROOT, path.join(dir, name)),
          raw: fs.readFileSync(path.join(dir, name), "utf8"),
        }));
    });
}

/** Answers /api/geo with a country, before anything on the page asks —
 *  the same double `base-market-price.spec.ts` uses. */
async function geoAnswers(page: Page, country: string | null): Promise<void> {
  await page.route("**/api/geo", (route: Route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ country }),
    })
  );
}

/* ---------------------------------------------------------------------------
 * 1. The routes, and the trap
 * ------------------------------------------------------------------------- */

test.describe("Routes — the section and the article answer at the translated slug", () => {
  for (const locale of LOCALES) {
    test(`DS-COPY-006: /${locale}${localizedPathname(locale, UPDATES_SECTION)} answers 200`, async ({
      request,
    }) => {
      const response = await request.get(sectionUrl(locale), { maxRedirects: 0 });
      expect(response.status(), `${sectionUrl(locale)} is the declared slug of ${locale}`).toBe(200);
    });

    test(`DS-COMPONENTE-057: every article of ${locale} answers at its own leaf`, async ({
      request,
    }) => {
      const listing = listUpdates(locale);
      expect(listing.length, `${locale} publishes no article; the section has nothing to prove`)
        .toBeGreaterThan(0);

      for (const document of listing) {
        const response = await request.get(articleUrl(document), { maxRedirects: 0 });
        expect(response.status(), articleUrl(document)).toBe(200);
      }
    });
  }

  test("DS-COMPONENTE-057: the leaf of ANOTHER language does not serve the piece", async ({
    request,
  }) => {
    // THE FAILURE THIS EXISTS FOR. `localizedPathname` translates the ancestor
    // and carries the leaf through, so `/pt/novidades/hour-passes` is exactly
    // what a hreflang built by string concatenation would publish. It has to be
    // a 404 and not a page: an address that answers 200 in two languages is two
    // canonical URLs for one piece.
    const foreign: string[] = [];
    for (const article of getUpdateArticles()) {
      const leaves = slugsByLocale(article.id);
      for (const locale of LOCALES) {
        const own = leaves[locale];
        for (const [otherLocale, otherLeaf] of Object.entries(leaves)) {
          if (otherLocale === locale || otherLeaf === own) continue;
          foreign.push(`${sectionUrl(locale)}/${otherLeaf}`);
        }
      }
    }
    expect(foreign.length, "no article has two different leaves to cross").toBeGreaterThan(0);

    for (const url of foreign) {
      const response = await request.get(url, { maxRedirects: 0 });
      expect(response.status(), `${url} serves a piece at an address nothing links to`).toBe(404);
    }
  });

  test("DS-COPY-006: the untranslated section word never serves a second copy", async ({
    request,
  }) => {
    // `/pt/updates` is the internal pathname under a locale that translates it.
    // next-intl answers a redirect to the canonical `/pt/novidades` rather than
    // a 404 — which is the behaviour we want and NOT what the spec's criterion
    // 1 predicted. What matters is the same either way: the internal word never
    // answers 200 with a second copy of the page.
    for (const locale of LOCALES) {
      const internal = `/${locale}${UPDATES_SECTION}`;
      if (internal === sectionUrl(locale)) continue;
      const response = await request.get(internal, { maxRedirects: 0 });
      expect([301, 302, 307, 308, 404], `${internal} answered ${response.status()}`).toContain(
        response.status()
      );
    }
  });
});

/* ---------------------------------------------------------------------------
 * 2. hreflang, canonical and the share card
 * ------------------------------------------------------------------------- */

test.describe("DS-COMPONENTE-057 — hreflang of an article comes from the registry", () => {
  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-057: hreflang on ${locale} names each locale's own leaf`, async ({
      request,
    }) => {
      for (const document of listUpdates(locale)) {
        const response = await request.get(articleUrl(document));
        expect(response.status()).toBe(200);
        const html = await response.text();

        const alternates = Object.fromEntries(
          [
            ...html.matchAll(/<link rel="alternate" hrefLang="([^"]+)" href="([^"]+)"/g),
          ].map((match) => [match[1], new URL(match[2]).pathname])
        );

        const leaves = slugsByLocale(document.id);
        const expected: Record<string, string> = {};
        for (const [other, leaf] of Object.entries(leaves)) {
          expected[other] = `${sectionUrl(other)}/${leaf}`;
        }
        // DS-COPY-047: only the locales the piece exists in. Pointing at a
        // translation that is not there is how all four are lost at once.
        expected["x-default"] = expected[DEFAULT_LOCALE] ?? Object.values(expected)[0];

        expect(alternates, `hreflang on ${articleUrl(document)}`).toEqual(expected);

        // And every address it names resolves.
        for (const href of new Set(Object.values(alternates))) {
          const alternate = await request.get(href, { maxRedirects: 0 });
          expect(alternate.status(), `alternate ${href}`).toBe(200);
        }
      }
    });

    test(`DS-COMPONENTE-056: og:image is the route, and og:image:alt is in ${locale}`, async ({
      page,
    }) => {
      for (const document of listUpdates(locale)) {
        await page.goto(articleUrl(document));

        const image = await page
          .locator('meta[property="og:image"]')
          .first()
          .getAttribute("content");
        // The INTERNAL path: the generated route is
        // `[locale]/updates/[slug]/opengraph-image`, and the localized pattern
        // `/novidades/[slug]` matches one segment, not two.
        expect(image, "og:image does not point at this article's own card").toContain(
          `/${locale}${UPDATES_SECTION}/${document.slug}/opengraph-image`
        );

        const alt = await page
          .locator('meta[property="og:image:alt"]')
          .first()
          .getAttribute("content");
        // The `alt` export of an opengraph-image is static and never sees
        // `params` — this is the whole reason the page keeps `openGraph.images`
        // instead of letting the file convention take over.
        expect(alt, "og:image:alt is not this locale's").toBe(document.ogAlt);
      }
    });

    test(`DS-COMPONENTE-056: the ${locale} share card answers 200 at 1200 × 630`, async ({
      request,
    }) => {
      for (const document of listUpdates(locale)) {
        const url = `/${locale}${UPDATES_SECTION}/${document.slug}/opengraph-image`;
        const response = await request.get(url);
        expect(response.status(), url).toBe(200);
        expect(response.headers()["content-type"]).toContain("image/png");

        // The IHDR of a PNG carries the size in bytes 16–23; reading it is
        // cheaper and more honest than trusting the route's `size` export.
        const body = await response.body();
        expect(body.readUInt32BE(16), `${url} width`).toBe(1200);
        expect(body.readUInt32BE(20), `${url} height`).toBe(630);
      }
    });

    test(`the ${locale} <title> does not name the brand twice`, async ({ request }) => {
      // The root layout appends "| TUGGI"; a frontmatter title that names it
      // would publish it twice in the one string a search result shows.
      for (const url of [sectionUrl(locale), ...listUpdates(locale).map(articleUrl)]) {
        const html = await (await request.get(url)).text();
        const title = /<title>([^<]*)<\/title>/.exec(html)?.[1] ?? "";
        expect(title, `${url} has no <title>`).not.toBe("");
        expect(
          (title.match(/TUGGI/gi) ?? []).length,
          `${url} publishes "${title}"`
        ).toBeLessThanOrEqual(1);
      }
    });
  }
});

/* ---------------------------------------------------------------------------
 * 3. The discovery surfaces
 * ------------------------------------------------------------------------- */

test.describe("The section is discoverable, or it is invisible", () => {
  test("DS-LAYOUT-011: /llms.txt carries the section and one line per article", async ({
    request,
  }) => {
    const body = await (await request.get("/llms.txt")).text();
    expect(body, "the AI-readable map has no Updates section").toContain("## Updates");
    expect(body).toContain(`${sectionUrl(DEFAULT_LOCALE)}`);

    for (const article of getUpdateArticles()) {
      const document = article.byLocale[DEFAULT_LOCALE] ?? Object.values(article.byLocale)[0];
      expect(body, `${article.id} is missing from /llms.txt`).toContain(articleUrl(document));
      expect(body, `${article.id} has no title in /llms.txt`).toContain(document.title);
    }
  });

  test("DS-LAYOUT-011: the sitemap carries the section and every article, per locale", async ({
    request,
  }) => {
    const xml = await (await request.get("/sitemap.xml")).text();

    for (const locale of LOCALES) {
      expect(xml, `${sectionUrl(locale)} is missing from the sitemap`).toContain(
        `https://www.tuggi.app${sectionUrl(locale)}<`
      );
      for (const document of listUpdates(locale)) {
        expect(xml, `${articleUrl(document)} is missing from the sitemap`).toContain(
          `https://www.tuggi.app${articleUrl(document)}<`
        );
      }
    }
  });

  test("DS-LAYOUT-011: the section is NOT an item of the main menu", () => {
    // The cold visitor's path is promise → proof → install. A reading
    // destination in a header that already carries six items, a language picker
    // and the download CTA is a seventh decision in it.
    //
    // Asserted on the registry and not on the rendered header, and the reason is
    // a false positive that cost a run: the language switcher lives INSIDE
    // `nav[data-nav-scope="desktop"]` and links the current page in the four
    // locales, so on the listing itself the header legitimately carries
    // `/en/updates`, `/pt/novidades`, `/es/novedades` and `/it/aggiornamenti`.
    // Those are the same page in another language, not a menu entry. What the
    // rule forbids is an ITEM, and the items are `NAV_ITEMS`.
    expect(
      NAV_ITEMS.map((item) => item.href),
      "the editorial section reached the main menu"
    ).not.toContain(UPDATES_SECTION);
  });

  for (const locale of LOCALES) {
    test(`DS-LAYOUT-011: the ${locale} footer carries the section`, async ({ page }) => {
      // The footer is one of the four doors, and the only one a human clicks —
      // the other three are the sitemap, /llms.txt and a direct link.
      await page.goto(`/${locale}`);
      await expect(
        page.locator(`footer a[href="${sectionUrl(locale)}"]`),
        "the section has no door in this locale"
      ).toHaveCount(1);
    });
  }

  test("the RSS feed of each locale answers with that locale's listing", async ({ request }) => {
    for (const locale of LOCALES) {
      const url = updatesFeedPath(locale);
      const response = await request.get(url);
      expect(response.status(), url).toBe(200);
      expect(response.headers()["content-type"]).toContain("application/rss+xml");

      const body = await response.text();
      // The address carries a dot, so the middleware never rewrites it — the
      // feed lives at the internal path, like /sitemap.xml and /llms.txt.
      expect(body).toContain(`<atom:link href="https://www.tuggi.app${url}"`);
      for (const document of listUpdates(locale)) {
        expect(body, `${articleUrl(document)} is missing from the ${locale} feed`).toContain(
          `https://www.tuggi.app${articleUrl(document)}`
        );
      }
    }
  });
});

/* ---------------------------------------------------------------------------
 * 4. The listing
 * ------------------------------------------------------------------------- */

test.describe("DS-COMPONENTE-051 / 052 — the listing and its card", () => {
  test("DS-COMPONENTE-052: the order is strictly descending by date, ties on the slug", () => {
    for (const locale of LOCALES) {
      const listing = listUpdates(locale);
      const sorted = [...listing].sort((a, b) =>
        a.publishedAt === b.publishedAt
          ? a.slug.localeCompare(b.slug)
          : b.publishedAt.localeCompare(a.publishedAt)
      );
      expect(listing.map((d) => d.slug), `${locale} is out of order`).toEqual(
        sorted.map((d) => d.slug)
      );

      // The other half of DS-COMPONENTE-052, and it is a trip-wire rather than
      // a property: while the section holds up to 24 pieces the listing is one
      // complete page. Above that it has to paginate BY ROUTE — one indexable
      // URL per page, with rel=next/prev — never infinite scroll and never a
      // "load more" with no URL, because content behind infinite scroll is not
      // crawled reliably. This goes red on the 25th article, which is when the
      // card is due.
      expect(
        listing.length,
        `${locale} crossed ${LISTING_CEILING} articles — the route-anchored pagination of ` +
          "DS-COMPONENTE-052 is now due"
      ).toBeLessThanOrEqual(LISTING_CEILING);
    }
  });

  test("DS-COMPONENTE-053: below the floor there is no filter control in the DOM", async ({
    page,
  }) => {
    // The floor is per locale, because the listing is per locale: 12 articles
    // AND at least 3 of each type. A control for a list that fits in one glance
    // is furniture. When a locale crosses the floor this goes red, which is the
    // trip-wire that opens the card.
    for (const locale of LOCALES) {
      const listing = listUpdates(locale);
      expect(
        showsTypeFilter(listing),
        `${locale} has ${listing.length} articles and crossed the floor of ` +
          `${FILTER_FLOOR.articles}/${FILTER_FLOOR.perType} — the filter of DS-COMPONENTE-053 is now due`
      ).toBe(false);

      await page.goto(sectionUrl(locale));
      await expect(
        page.locator('[data-block="update-type-filter"]'),
        `${locale} renders a filter the floor does not allow`
      ).toHaveCount(0);
    }
  });

  for (const [width, columns] of [
    [1280, 3],
    [700, 2],
    [360, 1],
  ] as const) {
    test(`DS-COMPONENTE-051: the grid has ${columns} column(s) at ${width} px, and no card under 300 px`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(sectionUrl(DEFAULT_LOCALE));

      const grid = page.locator("main div.grid").first();
      const measured = await grid.evaluate((node) => ({
        columns: getComputedStyle(node).gridTemplateColumns.split(" ").filter(Boolean).length,
        cardWidths: [...node.children].map((child) => child.getBoundingClientRect().width),
      }));

      // Three and not four, measured: at 1280 the rail gives 1216 px, and with
      // gap-6 three columns are 389 px — where the clamped summary breaks at
      // ~48 characters. Four give 286 px and three lines become a fragment.
      expect(measured.columns, `${width} px`).toBe(columns);
      for (const cardWidth of measured.cardWidths) {
        expect(cardWidth, `a card measures ${cardWidth} px at ${width} px`).toBeGreaterThanOrEqual(
          300
        );
      }
    });
  }

  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-051: on ${locale} every card is one tab stop named by its title`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1280, height: 900 });
      await page.goto(sectionUrl(locale));

      const listing = listUpdates(locale);
      for (const document of listing) {
        const card = page.locator(`main a[href="${articleUrl(document)}"]`);
        // One target per card: the affordance is not a second anchor, because
        // two links to one destination are two keyboard stops for one decision.
        await expect(card, `${document.slug} is linked more than once`).toHaveCount(1);

        // NOT toHaveAccessibleName: whitespace between inline children makes
        // that matcher normalise a real difference away. The name is anchored
        // on the h2 by aria-labelledby, so the h2's text IS the name.
        const labelledBy = await card.getAttribute("aria-labelledby");
        expect(labelledBy, "the card composes its name out of everything inside it").toBeTruthy();
        const name = await page.locator(`#${labelledBy}`).evaluate((node) => node.textContent ?? "");
        expect(name.trim()).toBe(document.title);
      }
    });

    test(`DS-COMPONENTE-051: on ${locale} the cards of a row are the same height`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1280, height: 900 });
      await page.goto(sectionUrl(locale));

      const heights = await page
        .locator("main div.grid > a")
        .evaluateAll((nodes) =>
          nodes.map((node) => Math.round(node.getBoundingClientRect().height))
        );
      expect(heights.length).toBeGreaterThan(0);
      expect(new Set(heights).size, `card heights in ${locale}: ${heights.join(", ")}`).toBe(1);
    });
  }

  test("DS-COPY-047: the empty state of a locale with no article is translated", () => {
    // Every locale publishes the first article today, so the empty state has no
    // page to be measured on. What CAN go wrong without anybody noticing is a
    // missing translation, which next-intl publishes as the key name — and that
    // is what this checks. The rendered state joins the day a locale is behind.
    for (const locale of LOCALES) {
      const messages = JSON.parse(
        fs.readFileSync(path.join(REPO_ROOT, "src/messages", `${locale}.json`), "utf8")
      );
      for (const key of ["body", "link"] as const) {
        const value = messages.Updates?.empty?.[key];
        expect(value, `Updates.empty.${key} is missing from ${locale}.json`).toBeTruthy();
        expect(value, `Updates.empty.${key} renders its own name in ${locale}`).not.toContain(
          "Updates.empty"
        );
      }
    }
  });
});

/* ---------------------------------------------------------------------------
 * 5. The article
 * ------------------------------------------------------------------------- */

test.describe("DS-A11Y-011 — the heading structure belongs to the template", () => {
  for (const locale of LOCALES) {
    test(`DS-A11Y-011: on ${locale} the article has one h1 and no level skip`, async ({ page }) => {
      // The loop variable is `piece` and not `document`: inside `page.evaluate`
      // the callback is type-checked in THIS scope, so an outer `document`
      // shadows the DOM one and the compiler resolves `querySelectorAll`
      // against an article.
      for (const piece of listUpdates(locale)) {
        await page.goto(articleUrl(piece));

        const headings = await page.evaluate(() =>
          Array.from(document.querySelectorAll("h1, h2, h3, h4, h5, h6")).map((element) => ({
            level: Number(element.tagName.slice(1)),
            text: (element.textContent ?? "").trim().slice(0, 60),
          }))
        );

        expect(headings.filter((h) => h.level === 1), "one <h1> per document").toHaveLength(1);
        expect(headings[0]?.level, "the first heading of the document is the <h1>").toBe(1);

        const skips = headings
          .slice(1)
          .map((heading, index) => ({ heading, previous: headings[index] }))
          .filter(({ heading, previous }) => heading.level > previous.level + 1)
          .map(({ heading, previous }) => `h${previous.level} → h${heading.level} (${heading.text})`);
        expect(skips, "heading levels step by one on the way down").toEqual([]);

        // The root layout owns `<main id="main-content">`; a second landmark of
        // the same role inside it is the defect trust-center/layout.tsx fixed.
        expect(await page.locator("main, [role=main]").count()).toBe(1);
        await expect(page.locator("html")).toHaveAttribute("lang", locale);
      }
    });
  }

  test("DS-COPY-047: the four locales of one piece have the same tree", () => {
    // Not the same text — the same SHAPE. If `pt` has four `h2` and `en` has
    // six, the same article answers different questions depending on the
    // language, and the citation that comes back to us is whichever one
    // somebody wrote with more enthusiasm.
    for (const article of getUpdateArticles()) {
      const shapes = Object.entries(article.byLocale).map(
        ([locale, document]) => [locale, documentShape(document.blocks)] as const
      );
      const [reference, referenceShape] = shapes[0];
      for (const [locale, shape] of shapes.slice(1)) {
        expect(
          shape,
          `${article.id}: ${locale} and ${reference} are not the same piece`
        ).toEqual(referenceShape);
      }
    }
  });

  test("BR-COMUNICACAO-009: the date of a piece is machine-readable and one per piece", async ({
    page,
  }) => {
    // This is the first surface of ours that DATES an assertion: a product page
    // describes today's offer and corrects itself when the product changes, and
    // an article of 2026-08-30 keeps saying 2026-08-30 forever. So the date is
    // in the markup, not only in a formatted sentence — and it is the same date
    // in the four languages, because they are one piece.
    for (const article of getUpdateArticles()) {
      for (const document of Object.values(article.byLocale)) {
        expect(document.publishedAt).toBe(article.publishedAt);
        await page.goto(articleUrl(document));
        await expect(page.locator(`time[datetime="${article.publishedAt}"]`).first()).toBeVisible();

        const served = await publishedText(page);
        expect(served, "the structured data does not carry the publication date").toContain(
          article.publishedAt
        );
      }
    }
  });
});

/**
 * `DS-LAYOUT-012` — the measure of running text is a **quotient**, not a width.
 *
 * The ceiling is `width ÷ font-size ≤ 33`, both computed in the browser. Width
 * alone proves nothing and that is what the first version of this guard got
 * wrong: the same 576 px carries 77 characters at 16 px and 66 at 18 px, and it
 * is the character that the 45–75 band of Bringhurst and the 80 ceiling of
 * SC 1.4.8 count. 33 em comes from the narrowest glyph measured on this copy,
 * 0,449 em — 33 ÷ 0,449 = 73,5 characters, inside the band and 8 % under the
 * WCAG ceiling.
 *
 * It runs in **four locales** because Portuguese is not the language of the
 * longest line: it has the WIDEST mean glyph (7,813 px against 7,474 px in
 * English), so it fits FEWER characters in the same column. English and Italian
 * are the ones that touch the ceiling, and measuring `pt` alone hid an English
 * paragraph of 80,2 characters.
 */
const MEASURE_CEILING = 33;

/**
 * Every element of an article that is **read line by line** — §11, 15-b.
 *
 * The notice and the two notes of the price table are on this list because they
 * are prose, whatever the shape of the box around them. Routing by block kind
 * instead of by genre is what published the notice at 768 px and 101 characters
 * a line in Italian — worse than the 102 of the legal pages that made the rule
 * exist.
 */
const RUNNING_TEXT: { label: string; selector: string }[] = [
  { label: "paragraph", selector: "article .prose p" },
  { label: "list item", selector: "article .prose li" },
  { label: "dek", selector: "article header > p" },
  { label: "notice body", selector: 'article [data-block="article-notice"] > div' },
  { label: "price-table note", selector: 'article [data-block="article-price-table"] > p' },
  { label: "figcaption", selector: "article figcaption" },
];

/**
 * The cover of the piece.
 *
 * `article > div > figure`, not `article > figure`: `DS-LAYOUT-013` wrapped the
 * reading column in a `<div>` so the grid can put the support column beside it,
 * and the cover moved down one level with the rest of the content. A figure
 * declared by the body sits deeper still, inside its own column wrapper, so
 * this path keeps naming exactly one element.
 */
const COVER = "article > div > figure";

/** The blocks that are objects, and whose column is the wide one. */
const WIDE_BLOCKS = ["article-figure", "article-quote", "article-change-table", "article-price-table"];

type Measured = { em: number; width: number; fontSize: number; text: string };

/** `getBoundingClientRect().width ÷ getComputedStyle().fontSize`, in the page. */
function measure(page: Page, selector: string): Promise<Measured[]> {
  return page.locator(selector).evaluateAll((nodes) =>
    nodes.map((node) => {
      const width = node.getBoundingClientRect().width;
      const fontSize = parseFloat(window.getComputedStyle(node).fontSize);
      return {
        em: width / fontSize,
        width,
        fontSize,
        // `textContent`, never an accessible name: with whitespace between
        // inline children the accname matcher normalises the difference away.
        text: (node.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 48),
      };
    })
  );
}

test.describe("DS-LAYOUT-012 — the reading column has a measured ceiling", () => {
  for (const locale of LOCALES) {
    test(`DS-LAYOUT-012: on ${locale} every running-text element measures at most ${MEASURE_CEILING} em`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1440, height: 1000 });

      // Every piece, not the newest one: the measure is a property of the
      // template, and which piece sorts first is decided by the calendar and by
      // the slug that breaks the tie. Article #2 declares no block, so its wide
      // column is the generated cover alone — the case that proves the ceiling
      // holds with nothing but the template inside it.
      let counted = 0;
      for (const document of listUpdates(locale)) {
        await page.goto(articleUrl(document));

        for (const { label, selector } of RUNNING_TEXT) {
          for (const element of await measure(page, selector)) {
            counted += 1;
            expect(
              element.em,
              `${locale} · ${document.slug} · ${label} runs ${element.em.toFixed(1)} em ` +
                `(${Math.round(element.width)} px ÷ ${element.fontSize} px): "${element.text}"`
            ).toBeLessThanOrEqual(MEASURE_CEILING);
          }
        }
      }
      expect(counted, "no running text was measured — the selectors went stale").toBeGreaterThan(0);
    });

    test(`DS-LAYOUT-012: on ${locale} prose is 18/32 and nothing cancels the measure`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1440, height: 1000 });
      await page.goto(articleUrl(listUpdates(locale)[0]));

      // 18/32 is `prose-lg`, and nobody had chosen the 16/28 it replaced: it is
      // the default of `@tailwindcss/typography` 0.5.19. The measure is the
      // quotient of width and body, so fixing the width and letting the body
      // pick itself decided half the rule and left the other half to a plugin.
      const type = await page.locator("article .prose").first().evaluate((node) => {
        const style = window.getComputedStyle(node);
        return { fontSize: style.fontSize, lineHeight: style.lineHeight, maxWidth: style.maxWidth };
      });
      expect(type.fontSize).toBe("18px");
      expect(type.lineHeight).toBe("32px");

      // `max-w-none` is the utility the legal pages use to cancel the measure,
      // and it is what takes their `<article>` to 822 px and 102 characters.
      expect(type.maxWidth, "something cancelled the measure of `prose`").not.toBe("none");
      // Scoped to the READING column and not to the whole `<article>`: the
      // support column of `DS-LAYOUT-013` carries `xl:max-w-none` on purpose —
      // above the breakpoint its width is the 368 px of the grid track, and a
      // 768 px cap left on it would be a number governing nothing. What this
      // guard defends is the measure of the text, and all of the text lives in
      // the first child. A substring match over the whole article would report
      // the rail and say "the measure was cancelled", which is a true count
      // about the wrong element.
      expect(
        await page
          .locator(
            'article > div:first-child [class*="max-w-none"], article > div:first-child[class*="max-w-none"]'
          )
          .count(),
        "something cancelled the measure inside the reading column"
      ).toBe(0);
    });

    test(`DS-LAYOUT-012: on ${locale} text shares one left edge and only objects bleed`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1440, height: 1000 });

      // `piece`, not `document`: inside `page.evaluate` the browser's own
      // `document` is what the callback needs, and a loop variable of that name
      // shadows it — the type error is the friendly half of that mistake.
      for (const piece of listUpdates(locale)) {
        await page.goto(articleUrl(piece));

        // Link back, badge and date, `h1`, dek, body and notice: one column,
        // one left edge. The header used to sit at 768 px with the body at 576,
        // so the piece opened on one axis and continued on another.
        const columns = await page.evaluate(() => {
          const box = (selector: string) => {
            const element = document.querySelector(selector);
            if (!element) return null;
            const rect = element.getBoundingClientRect();
            return { left: Math.round(rect.left), width: Math.round(rect.width) };
          };
          return {
            back: box("article header > a"),
            meta: box("article header > div"),
            title: box("article header > h1"),
            dek: box("article header > p"),
            body: box("article .prose"),
            notice: box('article [data-block="article-notice"]'),
          };
        });

        const text = Object.entries(columns).filter(([, value]) => value !== null);
        expect(text.length, "the header of the article vanished").toBeGreaterThan(4);
        const [, first] = text[0];
        for (const [name, value] of text) {
          expect(value!.left, `${locale} · ${piece.slug} · ${name} starts on another axis`).toBe(
            first!.left
          );
        }
        expect(columns.body!.width, "the reading column is not 576 px").toBe(576);

        // The cover is an object and keeps the wide column — as a sibling of
        // the header, not as its last child, and with no negative margin: a
        // negative margin breaks below a 768 px viewport.
        const cover = await page
          .locator(COVER)
          .first()
          .evaluate((node) => Math.round(node.getBoundingClientRect().width));
        expect(cover).toBe(768);
        expect(cover).toBeGreaterThan(columns.body!.width);

        for (const block of WIDE_BLOCKS) {
          const widths = await page
            .locator(`article [data-block="${block}"]`)
            .evaluateAll((nodes) => nodes.map((node) => Math.round(node.getBoundingClientRect().width)));
          for (const width of widths) {
            expect(width, `${block} left the figure column`).toBeLessThanOrEqual(768);
            expect(width, `${block} was demoted to the text column`).toBeGreaterThan(576);
          }
        }
      }
    });
  }

  /**
   * No published piece declares a figure or a quotation today, so the two
   * `<figcaption>` of the section have no DOM to be measured in. The class is
   * the assertion until one does: at 768 px they measured 54,9 em, which 15-b
   * refuses along with everything else that is read line by line.
   */
  test("DS-LAYOUT-012: the two figcaptions do not inherit the width of their figure", () => {
    for (const name of ["ArticleFigure", "ArticleQuote"]) {
      const source = fs.readFileSync(
        path.join(REPO_ROOT, `src/components/blocks/article/${name}.tsx`),
        "utf8"
      );
      const caption = source.match(/<figcaption className="([^"]+)"/);
      expect(caption, `${name} no longer renders a figcaption with a literal className`).not.toBeNull();
      expect(caption![1], `${name}: the caption inherits the 768 px of its figure`).toContain(
        "max-w-lg"
      );
      expect(caption![1], `${name}: the caption is smaller than the prose around it`).toContain(
        "text-base"
      );
    }
  });
});

/* ---------------------------------------------------------------------------
 * 5-b. The article occupies the rail, and the rail is navigation —
 *      DS-LAYOUT-013 and DS-COMPONENTE-059, §11 criteria 15-c, 15-d, 15-e, 15-f
 * ------------------------------------------------------------------------- */

/**
 * `DS-LAYOUT-013` — the article occupies the rail, by structure and never by a
 * wider line. `DS-COMPONENTE-059` — what the second track carries.
 *
 * `DS-LAYOUT-012` decided how WIDE the reading column is; `DS-LAYOUT-013`
 * decides where it STARTS and what fills what is left. The two are different
 * axes of the same page and neither replaces the other: the column is still
 * 576 px of text and 768 px of object, and it begins on the content edge of the
 * rail instead of floating in the middle of it. Centring a narrow column inside
 * the rail creates a second rail — the body opened at `left` 432 while the logo
 * of the header opened at 112, 320 px of ditch on each side, 53 % of the rail
 * empty — and that misalignment is what the eye reads as "not the same page".
 *
 * The proof is geometric and needs no screenshot: the `<article>` shares the
 * `left` and the `width` of the content box of the footer's shell, and so do
 * the `h1`, the body and the cover. The footer is the reference on purpose. It
 * is the surface furthest from this template that draws the same rail, so a
 * regression in the rail itself and a regression in this article cannot cancel
 * each other out.
 *
 * Anchoring alone is not the rule — it was measured and refused. Removing
 * `mx-auto` and stopping there leaves 672 px of dead space to the right at
 * 2560, which is worse than the symmetric ditch it replaced. So the second
 * track carries function.
 *
 * **What that function is changed on 2026-08-31 (#617), and the change is the
 * point of half of this file.** The track used to carry the download call, and
 * that put two filled buttons of the SAME act in the same corner: the orange
 * `Baixar App` the header pins to every scroll and a cyan one 278 px below it.
 * Now the track carries a rail of internal navigation — three destinations the
 * menu already publishes, no tint of action, no button, no number — and the
 * call goes back to the end of the reading. So this block proves two things at
 * once and they pull in opposite directions: the rail has to be THERE (15-d)
 * and it has to be QUIET (15-f), and the call has to exist EXACTLY ONCE, in the
 * reading column, at every viewport (15-e).
 */
const RAIL_WIDTH = 1216;

/** Above the breakpoint: the rail is constant, only the margin around it grows. */
const RAIL_VIEWPORTS = [
  { width: 1280, left: 32 },
  { width: 1440, left: 112 },
  { width: 2560, left: 672 },
];

/**
 * Below it the grid collapses to one column and the navigation rail is not
 * rendered at all. 1024 is the widest viewport with no rail and the one the
 * `xl:` threshold is easiest to get wrong on; 768 is the breakpoint of the
 * cover's own `sizes`; 360 is the narrowest phone the site supports. The three
 * are where a two-column grid that forgot to collapse produces horizontal
 * scroll instead of a visible break.
 */
const COLLAPSED_VIEWPORTS = [360, 768, 1024];

/** The support column of the rail: 1216 − 768 of text − 80 of gutter. */
const SUPPORT_WIDTH = 368;

/** The navigation rail — one attribute, so the test never guesses the tag. */
const RAIL = "nav[data-article-rail]";

/** The pager. `article nav` is ambiguous now: the rail is a `<nav>` too. */
const PAGER = "article nav[aria-label]";

/** The store call the article ends with — one node, at every viewport. */
const STORE_CTA = 'article a[href="/d/tuggi"], article a[href^="https://apps.apple"]';

/**
 * Every box criteria 15-c and 15-e compare, read in one pass so they are all
 * measured against the same layout.
 *
 * The rail is taken as the CONTENT box of the footer's shell — its padding
 * discounted — because that is the edge the reader compares against: the rail
 * is where the content starts, not where the wrapper starts.
 */
function railGeometry(page: Page, cover: string) {
  return page.evaluate(
    ({ coverSelector, railSelector, pagerSelector, ctaSelector }) => {
      const rect = (element: Element | null) => {
        if (!element) return null;
        const measured = element.getBoundingClientRect();
        return {
          left: Math.round(measured.left),
          right: Math.round(measured.right),
          width: Math.round(measured.width),
          height: Math.round(measured.height),
          top: Math.round(measured.top + window.scrollY),
          bottom: Math.round(measured.bottom + window.scrollY),
        };
      };
      const box = (selector: string) => rect(document.querySelector(selector));

      const shell = document.querySelector("footer > div");
      const shellRect = shell!.getBoundingClientRect();
      const shellStyle = window.getComputedStyle(shell!);
      const padLeft = parseFloat(shellStyle.paddingLeft);
      const padRight = parseFloat(shellStyle.paddingRight);

      // The card of the call is the parent of the store link, not a class the
      // test would have to keep in step with the markup.
      const call = document.querySelector(ctaSelector);
      const card = call?.parentElement ?? null;
      const cardBody = card?.querySelector("p") ?? null;

      return {
        rail: {
          left: Math.round(shellRect.left + padLeft),
          right: Math.round(shellRect.right - padRight),
          width: Math.round(shellRect.width - padLeft - padRight),
        },
        logo: box('header img[alt="TUGGI Logo"]'),
        article: box("article"),
        title: box("article header h1"),
        body: box("article .prose"),
        cover: box(coverSelector),
        railNav: box(railSelector),
        pager: box(pagerSelector),
        card: rect(card),
        cardBody: cardBody
          ? {
              ...rect(cardBody)!,
              fontSize: parseFloat(window.getComputedStyle(cardBody).fontSize),
            }
          : null,
        scrollWidth: document.documentElement.scrollWidth,
        innerWidth: window.innerWidth,
      };
    },
    { coverSelector: cover, railSelector: RAIL, pagerSelector: PAGER, ctaSelector: STORE_CTA }
  );
}

test.describe("DS-LAYOUT-013 — the article occupies the rail", () => {
  // One locale for the geometry, and that is deliberate: the grid is a property
  // of the TEMPLATE, not of the copy inside it. What changes per language is
  // the measure of the line, and `DS-LAYOUT-012` already runs its four locales
  // over that; the rail's own copy is checked in the four below.
  // Every published piece of the locale, though — article #2 declares no block,
  // so its reading column is the header and the generated cover alone, which is
  // the case that proves the grid holds with the least content in it.
  const pieces = listUpdates(DEFAULT_LOCALE);

  for (const { width, left } of RAIL_VIEWPORTS) {
    test(`DS-LAYOUT-013: at ${width} px the article starts on the rail and the navigation column closes it`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 1000 });

      for (const piece of pieces) {
        await page.goto(articleUrl(piece));
        const at = await railGeometry(page, COVER);
        const where = `${piece.slug} at ${width} px`;

        // The reference first. If the footer stopped drawing the rail, every
        // assertion below would still pass while the page was broken.
        expect(at.rail.width, `${where}: the footer no longer draws a ${RAIL_WIDTH} px rail`).toBe(
          RAIL_WIDTH
        );
        expect(at.rail.left, `${where}: the rail does not start where the card measured it`).toBe(
          left
        );

        expect(at.article!.left, `${where}: the article floats inside the rail`).toBe(at.rail.left);
        expect(at.article!.width, `${where}: the article does not span the rail`).toBe(
          at.rail.width
        );

        // The logo is the element always on screen, and it is what the reader
        // compares the article against without knowing they are doing it.
        expect(at.logo!.left, `${where}: the header logo left the rail`).toBe(at.rail.left);
        for (const [name, geometry] of [
          ["h1", at.title],
          ["body", at.body],
          ["cover", at.cover],
        ] as const) {
          expect(geometry, `${where}: the ${name} vanished`).not.toBeNull();
          expect(geometry!.left, `${where}: the ${name} starts on a second rail`).toBe(
            at.logo!.left
          );
        }

        // DS-LAYOUT-012 is untouched: anchoring the column is not widening it,
        // and neither is putting navigation next to it. #617 refused widening
        // for a measured reason — 36 em is 80,2 characters in the worst real
        // English paragraph, over the ceiling of SC 1.4.8 — and widening would
        // have taken nothing back from the rail anyway: the track is sized by
        // the object column, not by the text one.
        expect(at.body!.width, `${where}: the reading column was stretched to the rail`).toBe(576);
        expect(at.cover!.width, `${where}: the cover left the figure column`).toBe(768);

        // The right half of the rule: the space left over carries function, and
        // it reaches the far edge. Anchoring without it trades a symmetric
        // ditch for a hole on the right.
        expect(at.railNav, `${where}: the navigation rail is not in the document`).not.toBeNull();
        expect(at.railNav!.width, `${where}: the rail is not the track`).toBe(SUPPORT_WIDTH);
        expect(at.railNav!.right, `${where}: the rail does not close the page's rail`).toBe(
          at.rail.right
        );
        // Beside the article, not under it — row 1 of the grid.
        expect(at.railNav!.top, `${where}: the rail fell below the content`).toBe(at.article!.top);

        expect(at.scrollWidth, `${where}: the page scrolls sideways`).toBeLessThanOrEqual(
          at.innerWidth + 1
        );
      }
    });
  }

  for (const width of COLLAPSED_VIEWPORTS) {
    test(`DS-COMPONENTE-059: at ${width} px the rail is NOT RENDERED and the call keeps its place in the flow`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 800 });

      for (const piece of pieces) {
        await page.goto(articleUrl(piece));
        const at = await railGeometry(page, COVER);
        const where = `${piece.slug} at ${width} px`;

        expect(at.article!.left, `${where}: the article floats inside the rail`).toBe(at.rail.left);
        expect(at.article!.width, `${where}: the article does not span the rail`).toBe(
          at.rail.width
        );

        // The rail does not exist below the threshold — `DS-LAYOUT-013` regra
        // 4. The three destinations are in the header and in the `FatFooter` at
        // this width, and a stack of links glued to the pager, which is
        // navigation itself, is a third menu.
        //
        // "Does not exist" is asserted as the reader and the screen reader can
        // observe it — no box, no accessible name, no tab stop — and NOT as a
        // count of DOM nodes, because this page is `force-static`: one HTML
        // answers every viewport, so nothing on the server knows how wide the
        // window is. `display: none` is the only mechanism that reaches the
        // three at once; the alternative, a media query read in JavaScript,
        // would ship a rail that pops in after hydration and is absent from the
        // served HTML. The one thing that WOULD be a defect is two nodes with
        // one hidden by CSS — that is proved above, on the call.
        const railBelow = page.locator("[data-article-rail]");
        await expect(railBelow, `${where}: the rail was rendered twice`).toHaveCount(1);
        await expect(railBelow, `${where}: the rail paints below the threshold`).toBeHidden();
        await expect(
          page.locator("[data-article-rail] a:visible"),
          `${where}: the rail publishes a visible link below the threshold`
        ).toHaveCount(0);
        // Zero tab stops, proved by trying: a `display: none` subtree cannot
        // take focus, and a rail hidden by opacity or by a zero height could.
        const focusable = await page.evaluate(() => {
          const anchors = Array.from(
            document.querySelectorAll<HTMLAnchorElement>("[data-article-rail] a")
          );
          return anchors.filter((anchor) => {
            anchor.focus();
            return document.activeElement === anchor;
          }).length;
        });
        expect(focusable, `${where}: the rail is still in the tab order`).toBe(0);

        // The call, on the other hand, is CONTENT of the page: it stays, in the
        // reading flow, between the body and the pager. One node in both cases.
        expect(at.card, `${where}: the call left the page`).not.toBeNull();
        expect(
          at.card!.top,
          `${where}: the call is still beside the body, so the grid did not collapse`
        ).toBeGreaterThanOrEqual(at.body!.bottom);
        if (at.pager) {
          expect(at.pager.top, `${where}: the pager climbed above the call`).toBeGreaterThanOrEqual(
            at.card!.bottom
          );
        }

        expect(at.scrollWidth, `${where}: the page scrolls sideways`).toBeLessThanOrEqual(
          at.innerWidth + 1
        );
      }
    });
  }

  for (const width of [...COLLAPSED_VIEWPORTS, ...RAIL_VIEWPORTS.map((v) => v.width)]) {
    test(`DS-COMPONENTE-058 / DS-LAYOUT-013: at ${width} px there is ONE call node, at the end of the reading`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(articleUrl(pieces[0]));

      // The call is written once, in the flow, and the grid never moves it. Two
      // nodes with one hidden by media query would double the tab stop and fire
      // `updates_article` from a target the reader cannot see — which is what
      // regra 4 forbids in both of its legs.
      await expect(
        page.locator(STORE_CTA),
        "the page carries more than one store call"
      ).toHaveCount(1);
      await expect(
        page.locator(`${RAIL} a[href="/d/tuggi"], ${RAIL} button, ${RAIL} [href^="https://apps"]`),
        "the rail grew a call to action"
      ).toHaveCount(0);
      // One rail node in the document at every width — the threshold decides
      // whether it PAINTS, never how many there are. See the collapsed test
      // above for why a statically generated page cannot drop the node.
      await expect(page.locator(RAIL), "the rail was rendered twice").toHaveCount(1);
      if (width >= 1280) {
        await expect(page.locator(RAIL), "the rail vanished above the threshold").toBeVisible();
      } else {
        await expect(page.locator(RAIL), "the rail paints below the threshold").toBeHidden();
      }

      // SC 1.3.2: the DOM order IS the reading order, and it does not follow the
      // screen. The rail paints at the top right above the breakpoint and is
      // still read after the body — reordering the DOM to match the screen is
      // the defect, not the fix.
      const order = await page.evaluate(
        ({ railSelector, pagerSelector, ctaSelector }) => {
          const body = document.querySelector("article .prose, article header")!;
          const call = document.querySelector(ctaSelector)!;
          const rail = document.querySelector(railSelector);
          const pager = document.querySelector(pagerSelector);
          const FOLLOWING = Node.DOCUMENT_POSITION_FOLLOWING;
          const follows = (first: Element, second: Element) =>
            Boolean(first.compareDocumentPosition(second) & FOLLOWING);
          return {
            callAfterBody: follows(body, call),
            railAfterCall: rail ? follows(call, rail) : null,
            pagerAfterCall: pager ? follows(call, pager) : null,
            callInReadingColumn: Boolean(call.closest("article > div:first-child")),
          };
        },
        { railSelector: RAIL, pagerSelector: PAGER, ctaSelector: STORE_CTA }
      );
      expect(order.callAfterBody, "the call is read before the article it interrupts").toBe(true);
      expect(order.callInReadingColumn, "the call left the reading column").toBe(true);
      if (order.railAfterCall !== null) {
        expect(order.railAfterCall, "the rail is read before the article").toBe(true);
      }
      if (order.pagerAfterCall !== null) {
        expect(order.pagerAfterCall, "the pager is read before the call").toBe(true);
      }
    });
  }

  for (const width of [...COLLAPSED_VIEWPORTS, ...RAIL_VIEWPORTS.map((v) => v.width)]) {
    test(`DS-COMPONENTE-058: at ${width} px the call fits the reading column and its line is measured`, async ({
      page,
    }) => {
      await page.setViewportSize({ width, height: 900 });

      for (const piece of pieces) {
        await page.goto(articleUrl(piece));
        const at = await railGeometry(page, COVER);
        const where = `${piece.slug} at ${width} px`;

        expect(at.card, `${where}: the call left the page`).not.toBeNull();
        // The figure column, never the rail: `max-w-3xl` and no `mx-auto`.
        expect(at.card!.width, `${where}: the call is wider than the figure column`)
          .toBeLessThanOrEqual(768);
        expect(at.card!.left, `${where}: the call starts on a second rail`).toBe(at.rail.left);

        // And the sentence inside it obeys DS-LAYOUT-012 like any other running
        // text: 512 px at 16 px is 32,0 em, under the ceiling of 33.
        expect(at.cardBody, `${where}: the call has no body copy`).not.toBeNull();
        const measure = at.cardBody!.width / at.cardBody!.fontSize;
        expect(
          Number(measure.toFixed(1)),
          `${where}: the body of the call measures ${measure.toFixed(1)} em`
        ).toBeLessThanOrEqual(MEASURE_CEILING);
      }
    });
  }
});

/**
 * `DS-COMPONENTE-059` — the rail is navigation, and it is quiet.
 *
 * Every clause below is arithmetic, which is the whole design of the rule: "it
 * does not compete with the reading" is not a matter of taste once it is
 * written as a font size, a target box, a height and a list of forbidden
 * colours. The measurements are taken at 1440 × 1000, which is where the
 * prototype the spec records was measured.
 */
test.describe("DS-COMPONENTE-059 — the rail is a slice of the site map, not a second offer", () => {
  /** The two tints of action. A rail may not paint either, on any descendant. */
  const ACTION_TOKENS = ["--color-tuggi-primary", "--color-tuggi-secondary"];

  function railFacts(page: Page) {
    return page.evaluate(
      ({ railSelector, pagerSelector, callSelector, tokens }) => {
        const rail = document.querySelector(railSelector);
        if (!rail) return null;

        // The tokens resolved by the browser, so the test compares what is
        // painted and not a hex someone typed twice.
        const probe = document.createElement("span");
        document.body.appendChild(probe);
        const forbidden = tokens.map((token) => {
          probe.style.color = `var(${token})`;
          return window.getComputedStyle(probe).color;
        });
        probe.remove();

        const isOpaque = (colour: string) => {
          const parts = colour.match(/[\d.]+/g);
          if (!parts) return false;
          return parts.length < 4 || parseFloat(parts[3]) > 0;
        };

        const descendants = Array.from(rail.querySelectorAll("*"));
        const paint = [rail, ...descendants].map((node) => {
          const style = window.getComputedStyle(node);
          return {
            tag: node.tagName.toLowerCase(),
            background: style.backgroundColor,
            colour: style.color,
            shadow: style.boxShadow,
            borders: (["Top", "Right", "Bottom", "Left"] as const).map((side) => ({
              width: parseFloat(style[`border${side}Width` as "borderTopWidth"]),
              colour: style[`border${side}Color` as "borderTopColor"],
            })),
            fontSize: parseFloat(style.fontSize),
            opaqueBackground: isOpaque(style.backgroundColor),
          };
        });

        const heading = rail.querySelector("h2, h3");
        const links = Array.from(rail.querySelectorAll("a")).map((anchor) => {
          const box = anchor.getBoundingClientRect();
          return {
            href: anchor.getAttribute("href") ?? "",
            text: (anchor.textContent ?? "").trim(),
            width: Math.round(box.width),
            height: Math.round(box.height),
            fontSize: parseFloat(window.getComputedStyle(anchor).fontSize),
          };
        });

        const proseParagraph = document.querySelector("article .prose p");

        return {
          forbidden,
          paint,
          buttons: rail.querySelectorAll("button").length,
          heading: heading
            ? {
                tag: heading.tagName.toLowerCase(),
                id: heading.id,
                text: (heading.textContent ?? "").trim(),
                fontSize: parseFloat(window.getComputedStyle(heading).fontSize),
              }
            : null,
          labelledBy: rail.getAttribute("aria-labelledby"),
          links,
          height: Math.round(rail.getBoundingClientRect().height),
          viewportHeight: window.innerHeight,
          proseFontSize: proseParagraph
            ? parseFloat(window.getComputedStyle(proseParagraph).fontSize)
            : null,
          otherHrefs: {
            back:
              document.querySelector("article header a")?.getAttribute("href") ?? null,
            pager: Array.from(document.querySelectorAll(`${pagerSelector} a`)).map(
              (anchor) => anchor.getAttribute("href") ?? ""
            ),
            call: document.querySelector(callSelector)?.getAttribute("href") ?? null,
          },
        };
      },
      { railSelector: RAIL, pagerSelector: PAGER, callSelector: STORE_CTA, tokens: ACTION_TOKENS }
    );
  }

  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-059: on ${locale} the rail is a named landmark of at most three menu links`, async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1440, height: 1000 });
      const messages = JSON.parse(
        fs.readFileSync(path.join(REPO_ROOT, `src/messages/${locale}.json`), "utf8")
      );

      for (const piece of listUpdates(locale)) {
        await page.goto(articleUrl(piece));
        const facts = await railFacts(page);
        const where = `${locale}/${piece.slug}`;
        expect(facts, `${where}: there is no rail at 1440 px`).not.toBeNull();

        // A landmark with no accessible name is a landmark a screen-reader user
        // cannot pick from a list. `textContent` and not the accname matcher:
        // the matcher normalises a missing space between inline children away
        // and would call a defect a pass.
        expect(facts!.labelledBy, `${where}: the rail has no aria-labelledby`).not.toBeNull();
        expect(facts!.heading, `${where}: the aria-labelledby points at nothing`).not.toBeNull();
        expect(facts!.heading!.id, `${where}: the rail is named by the wrong element`).toBe(
          facts!.labelledBy
        );
        // The label is copy, and it is the ONLY new string of the rail — the
        // rest comes from the menu. A key that did not resolve renders its own
        // path, and next-intl 4.12 does not break the build over it.
        expect(facts!.heading!.text, `${where}: the rail title is rendering its i18n path`)
          .not.toContain("Updates.");
        expect(facts!.heading!.text, `${where}: the rail title is not the published copy`).toBe(
          messages.Updates.rail.title
        );

        // (b) of the criterion: the label of every link is the one the MENU
        // carries. Two names for the same place is the defect this forbids, so
        // the expectation is read from `Header.nav*` and from the registry, not
        // typed here.
        const expected = ARTICLE_RAIL_ITEMS.map((item) => ({
          href: `/${locale}${localizedPathname(locale, item.href)}`,
          text: messages.Header[item.labelKey] as string,
        }));
        expect(expected.length, "the rail registry lost its destinations").toBeGreaterThan(0);
        expect(expected.length, "Hick's law: three is the ceiling").toBeLessThanOrEqual(3);
        expect(
          facts!.links.map((link) => ({ href: link.href, text: link.text })),
          `${where}: the rail does not spell the menu`
        ).toEqual(expected);

        // (g) no digit, in any of the four languages. No price, no date, no
        // count: a number in the rail is a second declaration of a business
        // rule that nothing keeps in step.
        const text = [facts!.heading!.text, ...facts!.links.map((link) => link.text)].join(" ");
        expect(text, `${where}: the rail carries a number`).not.toMatch(/\d/);

        // (g) of DS-COMPONENTE-059: no destination is printed twice in the same
        // document. The pager already publishes the neighbouring pieces and the
        // header link already goes back to the section.
        const elsewhere = new Set(
          [facts!.otherHrefs.back, facts!.otherHrefs.call, ...facts!.otherHrefs.pager].filter(
            (href): href is string => Boolean(href)
          )
        );
        for (const link of facts!.links) {
          expect(
            elsewhere.has(link.href),
            `${where}: ${link.href} is already published elsewhere on this page`
          ).toBe(false);
        }
      }
    });
  }

  test("DS-COMPONENTE-059: the rail carries no surface, no tint of action and no button", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(articleUrl(listUpdates(DEFAULT_LOCALE)[0]));
    const facts = (await railFacts(page))!;
    expect(facts, "there is no rail at 1440 px").not.toBeNull();

    // (a) no card: no opaque background, no shadow, and the only border allowed
    // is the 1 px rule between items.
    for (const node of facts.paint) {
      expect(node.opaqueBackground, `<${node.tag}> in the rail paints a surface`).toBe(false);
      expect(node.shadow, `<${node.tag}> in the rail casts a shadow`).toBe("none");
      for (const border of node.borders) {
        expect(border.width, `<${node.tag}> in the rail draws a card border`).toBeLessThanOrEqual(
          1
        );
      }
    }

    // (b) no tint of action anywhere — this is the whole reason the rule was
    // rewritten. The focus ring is the exception and it is not painted here.
    for (const node of facts.paint) {
      for (const forbidden of facts.forbidden) {
        expect(node.background, `<${node.tag}> paints the rail with a brand tint`).not.toBe(
          forbidden
        );
        expect(node.colour, `<${node.tag}> writes the rail in a brand tint`).not.toBe(forbidden);
      }
    }

    // (c) no button of any kind.
    expect(facts.buttons, "the rail grew a button").toBe(0);
  });

  test("DS-COMPONENTE-059: the rail is smaller than the reading and fits the window", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(articleUrl(listUpdates(DEFAULT_LOCALE)[0]));
    const facts = (await railFacts(page))!;
    expect(facts, "there is no rail at 1440 px").not.toBeNull();

    // (d) the biggest type in the rail is smaller than the body of the article,
    // and the label is the smallest text on the screen.
    const biggest = Math.max(...facts.paint.map((node) => node.fontSize));
    expect(biggest, "the rail reads as loud as the article").toBeLessThanOrEqual(16);
    expect(facts.proseFontSize, "the body of the article is not 18 px any more").toBe(18);
    expect(facts.heading!.fontSize, "the label of the rail is not the smallest text")
      .toBeLessThanOrEqual(12);

    // (e) a comfortable target: SC 2.5.8 asks 24 × 24, and a vertical list of
    // links is not the *Inline* exception, so the 44 px of the HIG and of
    // Material are what a stack this cheap should cost.
    for (const link of facts.links) {
      expect(link.height, `"${link.text}" is a ${link.height} px target`).toBeGreaterThanOrEqual(
        44
      );
      expect(link.width, `"${link.text}" is a ${link.width} px target`).toBeGreaterThanOrEqual(24);
    }

    // (f) a sticky rail taller than the window has its foot cut off and does
    // not scroll.
    expect(
      facts.height,
      `the rail is ${facts.height} px of a ${facts.viewportHeight} px window`
    ).toBeLessThanOrEqual(facts.viewportHeight / 2);
  });
});

/**
 * The `data-block` of a rendered block is its component name in kebab case, and
 * that convention IS the contract: a block that paints under another name goes
 * red here rather than being quietly absent from the count below.
 */
function blockAttribute(name: AuthorableBlock): string {
  return name.replace(/(?!^)([A-Z])/g, "-$1").toLowerCase();
}

test.describe("DS-COMPONENTE-054 / 055 — the closed block set", () => {
  test("DS-COMPONENTE-054: the page renders exactly the blocks the piece declares", async ({
    page,
  }) => {
    // Against the TREE the parser produced, never against a list of blocks
    // somebody expected to find. Until 2026-08-30 this read the marker article,
    // which exercised all five blocks on purpose; the real copy of article #1
    // carries a notice, a before/after and the price table, and no figure and
    // no quotation — a decision of the copy deck (§2: there is no assertable
    // image for this piece, and an attributed quotation has no source), not an
    // omission to fix. Written this way the assertion survives that decision
    // AND still goes red if a block is declared and never painted.
    //
    // Every piece of the section, because the other half of the assertion —
    // nothing is painted that was NOT declared — can only be proved by a piece
    // that declares nothing, and article #2 is one.
    let declaredInSection = 0;

    for (const document of listUpdates(DEFAULT_LOCALE)) {
      await page.goto(articleUrl(document));

      const declared = document.blocks.filter((block) => block.kind === "component");
      declaredInSection += declared.length;
      for (const name of AUTHORABLE_BLOCKS) {
        const expected = declared.filter((block) => block.name === name).length;
        const selector = `article [data-block="${blockAttribute(name)}"]`;
        await expect(
          page.locator(selector),
          `${document.slug}: ${name} declared ${expected}×`
        ).toHaveCount(expected);
      }
    }

    // At least one block somewhere, or this test proves nothing about rendering.
    expect(declaredInSection, "no piece of the section declares a block at all").toBeGreaterThan(0);
  });

  test("DS-COMPONENTE-055: before/after is one table with a caption and two column headers", async ({
    page,
  }) => {
    await page.goto(articleUrl(articleDeclaring(DEFAULT_LOCALE, "ArticleChangeTable")));

    const table = page.locator("article table").first();
    await expect(table.locator("caption")).toHaveCount(1);
    await expect(table.locator('th[scope="col"]')).toHaveCount(2);
  });

  test("DS-COMPONENTE-055: at 360 px the pair of a row stays adjacent", async ({ page }) => {
    // The reading this block exists to prevent is two separate lists. A
    // `display: block` "responsive table" delivers exactly that and drops the
    // header association on the way, so the table stays a table at every width.
    await page.setViewportSize({ width: 360, height: 900 });
    await page.goto(articleUrl(articleDeclaring(DEFAULT_LOCALE, "ArticleChangeTable")));

    const row = page.locator("article table tbody tr").first();
    const boxes = await row
      .locator("td")
      .evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect()));
    expect(boxes).toHaveLength(2);
    // Side by side, not stacked: the two cells share a line.
    expect(
      Math.abs(boxes[0].top - boxes[1].top),
      "the two sides of one row split into two stacks"
    ).toBeLessThan(4);
  });

  for (const locale of LOCALES) {
    test(`DS-COMPONENTE-058: on ${locale} every article ends with one CTA and the pager its neighbours ask for`, async ({
      page,
    }) => {
      const listing = listUpdates(locale);
      expect(listing.length, `${locale} publishes nothing to page through`).toBeGreaterThan(0);

      for (const document of listing) {
        await page.goto(articleUrl(document));

        // One store CTA, and it is the one the site already publishes. No
        // newsletter, no "follow us", and no third-party share widget — a share
        // script would enter the AttributionGateProvider and the CookieBanner
        // this site already operates, and would cost weight on a phone.
        const storeCta = page.locator(
          'article a[href="/d/tuggi"], article a[href^="https://apps.apple"]'
        );
        await expect(storeCta, `${document.slug} does not end in one CTA`).toHaveCount(1);

        // The pager renders the neighbours the listing actually has: nothing at
        // all while the section holds one piece, one side while it holds two,
        // both sides from the third on. Until 2026-08-30 the section held one
        // article and this could only prove the empty case.
        const { previous, next } = pagerFor(listing, document.slug);
        // `article nav` stopped being unambiguous when the support column became a
        // navigation rail (DS-COMPONENTE-059). The pager is the one named by
        // `aria-label`; reaimed, not loosened.
        const nav = page.locator("article nav[aria-label]");
        await expect(nav, `${document.slug} pages to nowhere`).toHaveCount(
          previous || next ? 1 : 0
        );
        if (!previous && !next) continue;

        const neighbours = [previous, next].filter(
          (neighbour): neighbour is UpdateDocument => Boolean(neighbour)
        );
        await expect(nav.locator("a")).toHaveCount(neighbours.length);
        for (const neighbour of neighbours) {
          // Its own locale's leaf, and the neighbour's title spelled out. A
          // pager link that crossed languages would publish the 404 of
          // DS-COMPONENTE-057 from inside the article, and one labelled by an
          // arrow alone makes the reader open a page to find out what it is.
          const link = nav.locator(`a[href="${articleUrl(neighbour)}"]`);
          await expect(link, `${document.slug} does not link ${neighbour.slug}`).toHaveCount(1);
          await expect(link).toContainText(neighbour.title);
        }
      }
    });
  }

  test("DS-COMPONENTE-058: the pager is previous-older / next-newer", () => {
    const listing = [
      { slug: "c", publishedAt: "2026-03-01" },
      { slug: "b", publishedAt: "2026-02-01" },
      { slug: "a", publishedAt: "2026-01-01" },
    ] as unknown as UpdateDocument[];

    expect(pagerFor(listing, "b").previous?.slug, "previous is the older piece").toBe("a");
    expect(pagerFor(listing, "b").next?.slug, "next is the newer piece").toBe("c");
    expect(pagerFor(listing, "c").next, "the newest piece has nothing newer").toBeNull();
    expect(pagerFor(listing, "a").previous, "the oldest piece has nothing older").toBeNull();
  });
});

test.describe("DS-MARCA-009 — alt, and what the generated cover is not", () => {
  for (const locale of LOCALES) {
    test(`DS-MARCA-009: every content image on ${locale} carries a real alt`, async ({ page }) => {
      for (const document of listUpdates(locale)) {
        await page.goto(articleUrl(document));

        const alts = await page
          .locator("article img")
          .evaluateAll((nodes) => nodes.map((node) => (node as HTMLImageElement).alt));

        for (const alt of alts) {
          expect(alt.trim(), "a content image has no description").not.toBe("");
          // The screen reader heard the title two elements ago.
          expect(alt.trim().toLowerCase()).not.toBe(document.title.trim().toLowerCase());
        }

        if (document.cover === "generated") {
          // The generated field carries no text and no logo, and is therefore
          // decorative: it is drawn inline and hidden from assistive technology
          // rather than described with an empty string over HTTP.
          // `article > figure`, not `article header figure`: the cover is an
          // object and left the header when the header went to the text column
          // (DS-LAYOUT-012). It is the only direct `<figure>` child of the
          // article — a body figure is wrapped in its column `<div>`.
          const cover = page.locator(`${COVER} svg`).first();
          await expect(cover).toHaveAttribute("aria-hidden", "true");
          await expect(page.locator(`${COVER} img`)).toHaveCount(0);
        }
      }
    });
  }
});

/* ---------------------------------------------------------------------------
 * 6. The price — BR-MONETIZACAO-069, and BR-COMUNICACAO-010's mechanical half
 * ------------------------------------------------------------------------- */

const PRICE_IN_PROSE = /(R\$|US\$|\bUSD\b|\bBRL\b|\bEUR\b|€|£|\$\s?\d)|\b\d+[.,]\d{2}\b/;

test.describe("BR-MONETIZACAO-069 — the article reads the price table, it never types it", () => {
  test("BR-COMUNICACAO-010: no amount is written into any .mdx", () => {
    // The dispensation of DS-COPY-048 does not exist for a price: a price on
    // the site is born in `src/lib/pricing.ts` and nowhere else, and an article
    // has no reason to type one. A number in content survives the market it
    // belongs to and is never formatted by `Intl`.
    const offenders = contentFiles()
      .flatMap(({ file, raw }) =>
        raw
          .split("\n")
          .map((line, index) => ({ file, line: index + 1, text: line }))
          .filter(({ text }) => PRICE_IN_PROSE.test(text))
      )
      .map(({ file, line, text }) => `${file}:${line}: ${text.trim()}`);

    expect(offenders).toEqual([]);
  });

  test("BR-MONETIZACAO-069: outside a base market the table shows the store note, with no number", async ({
    page,
  }) => {
    await geoAnswers(page, "MX");
    await page.goto(articleUrl(articleDeclaring(DEFAULT_LOCALE, "ArticlePriceTable")));

    const block = page.locator('[data-block="article-price-table"]');
    await expect(block).toHaveCount(1);
    const text = await block.innerText();

    expect(text, "an amount was published outside the three base markets").not.toMatch(
      PRICE_IN_PROSE
    );
    expect(text, "the store note names neither store").toContain("App Store");
    expect(text, "the store note names neither store").toContain("Google Play");
  });

  test("BR-MONETIZACAO-069: inside a base market the table shows the three amounts", async ({
    page,
  }) => {
    await geoAnswers(page, "BR");
    await page.goto(articleUrl(articleDeclaring(DEFAULT_LOCALE, "ArticlePriceTable")));

    const block = page.locator('[data-block="article-price-table"]');
    // Written out here independently of `src/lib/pricing.ts`, so changing a
    // number on either side goes red — the table is what the site charges
    // people to believe (BR-MONETIZACAO-048).
    for (const amount of ["9.90", "19.90", "29.90"]) {
      await expect(block, `the ${amount} row`).toContainText(amount);
    }
  });

  test("BR-MONETIZACAO-069: the geo answer decides, and an unknown country is not a market", async ({
    page,
  }) => {
    await geoAnswers(page, null);
    await page.goto(articleUrl(articleDeclaring(DEFAULT_LOCALE, "ArticlePriceTable")));

    const text = await page.locator('[data-block="article-price-table"]').innerText();
    expect(text, '"I do not know where you are" published an offer').not.toMatch(PRICE_IN_PROSE);
  });
});

/* ---------------------------------------------------------------------------
 * 7. The content contract — parse time, so it breaks the build
 * ------------------------------------------------------------------------- */

test.describe("DS-COPY-046 / DS-A11Y-011 — what the content files may contain", () => {
  test("DS-A11Y-011: no `#` opens a line in any body", () => {
    for (const { file, raw } of contentFiles()) {
      const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "");
      const offenders = body
        .split("\n")
        .map((line, index) => ({ line: index + 1, text: line }))
        .filter(({ text }) => /^#(?!#)/.test(text))
        .map(({ line, text }) => `${file}:${line}: ${text}`);
      expect(offenders, "the `h1` belongs to the template").toEqual([]);
    }
  });

  test("DS-COPY-046: asides are counted per paragraph, with a ceiling per piece", () => {
    // The unit is the paragraph, because an article has no i18n key. The four
    // marks count TOGETHER — a guard matching only `[—–]` passes green in
    // Spanish, which translates the same asides with a colon.
    for (const { file, raw } of contentFiles()) {
      const { blocks } = parseEditorialDocument(raw, file);
      const paragraphs = blocks
        .filter((block) => block.kind === "paragraph")
        .map((block) =>
          block.kind === "paragraph"
            ? block.children
                .map((node) => (node.kind === "text" ? node.value : ""))
                .join("")
            : ""
        );

      expect(paragraphs.length, `${file} has no paragraph to measure`).toBeGreaterThan(0);

      const withAside = paragraphs.filter((text) => asideMarks(text) > 0);
      for (const text of paragraphs) {
        expect(asideMarks(text), `${file}: "${text.slice(0, 70)}"`).toBeLessThanOrEqual(
          ASIDE_CEILING
        );
        expect(longestBreath(text), `${file}: "${text.slice(0, 70)}"`).toBeLessThanOrEqual(
          BREATH_CEILING
        );
      }
      expect(
        withAside.length * 3,
        `${file}: ${withAside.length} of ${paragraphs.length} paragraphs carry an aside`
      ).toBeLessThanOrEqual(paragraphs.length);
    }
  });

  test("DS-COMPONENTE-054: an unknown tag, a style or a className is a parse error", () => {
    const frontmatter = [
      "---",
      "slug: x",
      "title: T",
      "summary: S",
      "type: news",
      "publishedAt: 2026-01-01",
      "cover: generated",
      "ogAlt: A",
      "---",
      "",
    ].join("\n");

    const refused: [string, string][] = [
      ["an undeclared component", '<ArticleCarousel src="a" />'],
      ["an inline style", '<ArticleNotice body="a" style="color:red" />'],
      ["a utility class", '<ArticleNotice body="a" className="text-red-500" />'],
      ["a figure with no alt", '<ArticleFigure src="/a.png" />'],
      ["an anonymous quotation", '<ArticleQuote quote="a" />'],
      ["a blank cell in before/after", '<ArticleChangeTable caption="c" beforeLabel="b" afterLabel="a" rows={[["x", ""]]} />'],
      ["an `h1` in the body", "# a heading the template owns"],
      ["an `h3` with no `h2` above it", "### orphan"],
    ];

    for (const [why, body] of refused) {
      expect(
        () => parseEditorialDocument(frontmatter + body + "\n", "<test>"),
        `${why} was accepted`
      ).toThrow();
    }
  });

  test("DS-COPY-048: a waiver with no reason is refused, and one with a reason is kept", () => {
    const base = [
      "---",
      "slug: x",
      "title: T",
      "summary: S",
      "type: news",
      "publishedAt: 2026-01-01",
      "cover: generated",
      "ogAlt: A",
    ].join("\n");

    const withReason = parseEditorialDocument(
      `${base}\nwaiver:\n  - rule: ACCESS_IN_DAYS\n    reason: "BR-MONETIZACAO-062 — the piece explains the extinction"\n---\n\nA paragraph.\n`,
      "<test>"
    );
    expect(withReason.frontmatter.waiver).toEqual([
      {
        rule: "ACCESS_IN_DAYS",
        reason: "BR-MONETIZACAO-062 — the piece explains the extinction",
      },
    ]);
  });
});
